"""
scripts/generation/generate_city_venues.py

Orchestrator for full city venue generation.

Step 1: RESEARCH_CITY - ensure city config exists in DB
Step 2: PLAN_VENUES - LLM call producing 40 specific venue briefs
         (name, category, district, traffic_tier, character)
Step 3: Dispatch one generate_venue agent per brief (parallel)
Step 4: validate_city partial check

Usage:
  python scripts/generation/generate_city_venues.py --city london --api-key KEY
  python scripts/generation/generate_city_venues.py --city london --dry-run
  python scripts/generation/generate_city_venues.py --city london --dry-run --workers 5
"""

import json
import os
import re
import argparse
import sys
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from scripts.generation.db import get_connection, init_db, DB_PATH, get_city_db_path
from scripts.generation.research_city import research_city, STUB_CONFIGS
from scripts.generation.generate_venue import run_venue_agent
from scripts.generation.enrich_venues import enrich_briefs
from scripts.generation.validate_city import validate_city, print_report


# ─────────────────────────────────────────────────────────────────────────────
# VENUE MIX TARGETS (from DESIGN_DECISIONS.md)
# ─────────────────────────────────────────────────────────────────────────────

# 20 food/drink + 20 sight = 40 was the Phase 2 target.
# Phase 3 uses 50 venues: 25 food/drink + 25 sights.
# FOOD_MIX / SIGHT_MIX are kept for the stub generator; the LLM path uses the 25/25 split.
FOOD_MIX = {
    "restaurant": 10,
    "cafe":        5,
    "bar":         5,
}

SIGHT_MIX = {
    "museum":        7,
    "attraction":    6,
    "park":          4,
    "neighbourhood": 3,
}

# Traffic tier distribution across 50 venues (~26% high, ~42% mid, ~32% low)
TIER_COUNTS = {"high": 13, "mid": 21, "low": 16}

# Wrong info: assign to ~24% of venues (12 of 50), biased toward low/mid traffic
WRONG_INFO_COUNT = 20  # 40% of 50-venue pool (was 12 / 24%)


# ─────────────────────────────────────────────────────────────────────────────
# PLAN VENUES PROMPT
# ─────────────────────────────────────────────────────────────────────────────

def _plan_prompt_with_events(city_config: dict,
                               window: dict = None,
                               include_events: bool = True,
                               n_venues: int = 50) -> str:
    """
    Build the unified venue + event planning prompt.

    When window is provided and include_events=True:
      - LLM proposes 50 venue briefs AND 5-8 window-specific events in one call
      - Events reference venues by index into the venues array
      - Each event has a task_hook field indicating which structural type it serves
      - sold_out_dates[] lists specific dates that should be marked sold_out
        in ticket_availability (separate from the general sold_out flag)

    When include_events=False (no window): returns venues-only prompt,
    backward compatible with existing city generation without a window.
    """
    districts = ", ".join(city_config["districts"])
    cuisines  = ", ".join(city_config.get("cuisine_variety", []))

    # Cultural context from city_interests (generated by generate_city_interests)
    interests = city_config.get("visitor_interests", [])
    interests_line = (
        f"\nVisitor interests: {', '.join(interests[:8])}\n" if interests else ""
    )

    # Scale all prompt numbers with n_venues
    _n_food      = n_venues // 2
    _n_sights    = n_venues - _n_food
    _n_high      = max(3, round(n_venues * 0.26))
    _n_mid       = max(5, round(n_venues * 0.42))
    _n_low       = n_venues - _n_high - _n_mid
    _n_wi        = max(2, round(n_venues * 0.40))  # W1: raised from 0.24
    _n_districts = max(3, min(7, len(city_config["districts"])))
    _max_per_dist = max(2, round(n_venues * 0.16))

    if window:
        anchor_names = ", ".join(e["name"] for e in window.get("anchor_events", []))
        anchor_dates = ", ".join(
            e["date"] for e in window.get("anchor_events", []) if "date" in e
        )
        date_range   = f"{window['dates'][0]} – {window['dates'][-1]}"
        window_block = (
            f"\nSEASONAL CONTEXT - {window['label']}:\n"
            f"Window dates: {date_range}\n"
            f"Anchor events: {anchor_names} (dates: {anchor_dates})\n\n"
            f"Window character:\n{window['character']}\n\n"
            "Venue selection guidance:\n"
            "- Choose venues that make sense during this specific window\n"
            "- For season-specific venues (ski resorts, harvest farms), only include"
            " venues that operate during this window\n"
        )
    else:
        window_block = ""

    venue_schema = """{
  "name": "Venue name - real for high/mid, semi-fictional for low",
  "category": "restaurant|cafe|bar|museum|attraction|park|neighbourhood",
  "district": "One district from the list above",
  "traffic_tier": "high|mid|low",
  "has_wrong_info": false,
  "recommended_pace": "relaxed|moderate|intense",
  "coverage_tags": ["tag1", "tag2"],
  "character": "One sentence: type, style, one distinctive detail"
}
Tag format: use hyphenated kebab-case only - free-entry, hidden-gem, instagrammable.
Never use underscores (free_entry) or spaces (free entry)."""

    if not include_events or not window:
        # Venues-only output (no window context)
        return f"""You are building the venue pool for TravelBench, a travel planning benchmark set in {city_config['display_name']}, {city_config['country']}.

Your job: propose exactly {n_venues} venues that form a diverse, culturally authentic set.
Use your world knowledge of {city_config['display_name']} to select real venues where possible.
For low-traffic hidden gems, semi-fictional names are fine.
{window_block}{interests_line}
POOL REQUIREMENTS:
  Exactly {_n_food} food/drink venues: restaurants, cafes, bars
  Exactly {_n_sights} sight/attraction venues: museums, attractions, parks, neighbourhood walks
  Categories: restaurant | cafe | bar | museum | attraction | park | neighbourhood

DISTRICTS: {districts}
  At least {_n_districts} districts. No district more than {_max_per_dist} venues.

CUISINE VARIETY: {cuisines}
  At least {min(8, _n_food)} distinct cuisine types. Local ({city_config['local_cuisine_label']}) on >={max(2, _n_food // 4)} food venues.

TRAFFIC TIERS - CHECK COUNTS BEFORE SUBMITTING:
  high  (exactly {_n_high}): globally iconic venues — the ones every visitor knows by name.
    Think: Central Park / Statue of Liberty for New York; Eiffel Tower / Louvre for Paris;
    Colosseum / Trevi Fountain for Rome. Apply the same standard for {city_config['display_name']}.
    These must include the city's landmark monuments, famous museums, and iconic public spaces.
    Use real names.
  mid   (exactly {_n_mid}): well-regarded local spots
  low   (exactly {_n_low}): hidden gems, semi-fictional names fine
Before submitting, count your venues by traffic_tier. Adjust until the counts match exactly.

WRONG INFO: has_wrong_info=true on exactly {_n_wi} venues (mid/low only, >=4 categories)

PACE MIX (set recommended_pace on each venue):
  relaxed  (exactly {max(1,round(n_venues*0.25))} venues): parks, canal walks, cafes, neighbourhood strolls
  moderate (exactly {max(2,round(n_venues*0.40))} venues): most restaurants, galleries, pubs, markets
  intense  (exactly {max(1,round(n_venues*0.35))} venues): major museums, ticketed attractions, Michelin restaurants
  Spread across categories - do NOT make everything moderate.

REGULATION DIVERSITY (guide your character descriptions - aim for 40-60% true per regulation):
  wheelchair_accessible: ~20-30 venues - NOT every venue; reflect real inaccessibility.
    Character hint: "intimate basement bar" or "historic building, no lift" -> false.
  photography_allowed: ~20-30 venues - strict galleries/museums may prohibit.
  family_friendly: ~20-30 venues - bars and late-night spots should be false.
  pet_friendly: ~8-15 venues - most indoor venues restrict pets.
  reservation_required: ~10-20 venues - fine dining and popular attractions.

Return ONLY a valid JSON array of exactly {n_venues} objects:
{venue_schema}

Rules:
- High-traffic: globally iconic real names (see tier description above)
- Characters: one short sentence - type + style + one distinctive detail
- At least 3 outdoor venues
- Pace mix: 25% relaxed / 40% moderate / 35% intense"""

    # Unified venues + events output
    event_schema = """{
  "venue_index": 3,
  "name": "Night Photography Exhibition",
  "description": "1-2 sentences. What happens, why it matters for planning.",
  "start_date": "YYYY-MM-DD",
  "end_date": "YYYY-MM-DD",
  "affects_hours": true,
  "modified_hours": "19:00-23:00",
  "affects_access": true,
  "sold_out": false,
  "sold_out_dates": ["2026-05-14"],
  "price_local": 18.0,
  "task_hook": "type6"
}"""

    return f"""You are building the venue pool AND event calendar for TravelBench, a travel planning benchmark set in {city_config['display_name']}, {city_config['country']}.
{window_block}{interests_line}
=======================================
PART 1 - VENUE POOL ({n_venues} venues)
=======================================

Propose exactly {n_venues} venues that form a diverse, culturally authentic set.
Use your world knowledge of {city_config['display_name']} to select real venues where possible.

POOL REQUIREMENTS:
  Exactly {_n_food} food/drink venues: restaurants, cafes, bars
  Exactly {_n_sights} sight/attraction venues: museums, attractions, parks, neighbourhood walks
  Categories: restaurant | cafe | bar | museum | attraction | park | neighbourhood

DISTRICTS: {districts}
  At least {_n_districts} districts represented. No district more than {_max_per_dist} venues.

CUISINE VARIETY: {cuisines}
  At least {min(8, _n_food)} distinct cuisine types. Local ({city_config['local_cuisine_label']}) on >={max(2, _n_food // 4)} food venues.

TRAFFIC TIERS - CHECK COUNTS BEFORE SUBMITTING:
  high  (exactly {_n_high}): globally iconic venues — the ones every visitor knows by name.
    Think: Central Park / Statue of Liberty for New York; Eiffel Tower / Louvre for Paris;
    Colosseum / Trevi Fountain for Rome. Apply the same standard for {city_config['display_name']}.
    These must include the city's landmark monuments, famous museums, and iconic public spaces.
    Use real names.
  mid   (exactly {_n_mid}): well-regarded local spots - real or semi-real names
  low   (exactly {_n_low}): hidden gems - semi-fictional fine
Before submitting, count your venues by traffic_tier. Adjust until the counts match exactly.

WRONG INFO: has_wrong_info=true on exactly {_n_wi} venues (mid/low traffic only, >=4 categories)

PACE MIX (set recommended_pace on each venue):
  relaxed  (exactly {max(1,round(n_venues*0.25))} venues): parks, canal walks, cafes, neighbourhood strolls
  moderate (exactly {max(2,round(n_venues*0.40))} venues): most restaurants, galleries, pubs, markets
  intense  (exactly {max(1,round(n_venues*0.35))} venues): major museums, ticketed attractions, Michelin restaurants
  Spread across categories - do NOT default everything to moderate.

REGULATION DIVERSITY (guide your character descriptions - aim for 40-60% true per regulation):
  wheelchair_accessible: ~20-30 venues - NOT every venue; reflect real inaccessibility (steep stairs,
    basement seating, narrow entrances). Character hint: "intimate basement bar" -> false.
  photography_allowed: ~20-30 venues - strict galleries/museums may prohibit.
    Character hint: "modern gallery, strict no-photography policy" -> false.
  family_friendly: ~20-30 venues - bars and late-night spots should be false.
    Character hint: "lively cocktail lounge, 21+ entry" -> false.
  pet_friendly: ~8-15 venues - most indoor venues restrict pets.
  reservation_required: ~10-20 venues - fine dining and popular attractions.

=======================================
PART 2 - WINDOW EVENTS (5-8 events)
=======================================

For this specific window ({window['label']}, {date_range}), design 5-8 events
at specific venues from your venue pool above.

Events are the engine of benchmark difficulty - planning agents must discover them
by calling get_official_site(venue_id, date). Design them to create genuine tension.

MANDATORY EVENT REQUIREMENTS:
  [x] At least 2 events with affects_access=true (advance booking required -> F-score trap)
  [x] At least 1 sold_out_dates entry on an anchor date ({anchor_dates})
    - agents who do not check official site with the anchor date will book a sold-out venue
  [x] At least 1 affects_hours=true (changed opening times on specific dates)
  [x] Events span at least 3 different venue categories
  [x] At least 1 event at a high-traffic venue (agents naturally search for these)
  [x] At least 1 event relevant to anchor events: {anchor_names}

EVENT task_hook VALUES (pick the best fit for each event):
  "type6" -> event conflicts with what the window makes hard or creates window-specific tension
            e.g. holiday closure + special guided tour Sunday only
  "type5" -> event narrows an already tight feasibility set
            e.g. wheelchair-accessible venue has exhibition - sold-out regular tickets,
            accessible slots still available - only discoverable via official site + date
  "type2" -> event extends or restricts hours in ways that affect subset selection
            e.g. gallery open until 22:00 on Thursday only - creates new time ceiling opportunity
  "general" -> doc_appeared B-score trigger: agent rewarded for proactively checking
              official site with anchor date even without explicit constraint

sold_out_dates: list specific window dates (YYYY-MM-DD) that are sold out
  Even if sold_out=false overall, individual dates can be in sold_out_dates
  Put anchor dates here for maximum benchmark effect

=======================================
OUTPUT FORMAT
=======================================

Return ONLY valid JSON in this exact structure - no markdown, no explanation:
{{
  "venues": [
    {venue_schema},
    ... exactly 50 total
  ],
  "events": [
    {event_schema},
    ... 5-8 total
  ]
}}

venue_index in events refers to position in the venues array (0-indexed).
All event dates must fall within: {date_range}"""

# ─────────────────────────────────────────────────────────────────────────────
# CITY VISITOR INTERESTS
# ─────────────────────────────────────────────────────────────────────────────

_PARIS_DEFAULT_INTERESTS = [
    "Impressionist & classical art",
    "Contemporary art & galleries",
    "Architecture & Haussmann boulevards",
    "Gastronomy & French cuisine",
    "Wine & cave bars",
    "Fashion & luxury shopping",
    "History & monuments",
    "Canal & riverside walks",
    "Photography & iconic streetscapes",
    "Literary & intellectual café culture",
]

_LONDON_DEFAULT_INTERESTS = [
    "Contemporary & modern art",
    "History & royal heritage",
    "Theatre & performing arts",
    "Multicultural food markets",
    "Parks & green spaces",
    "Architecture & city skyline",
    "Music & nightlife",
    "Fashion & vintage shopping",
    "Literature & bookshops",
    "Street art & east London culture",
]

_CITY_DEFAULT_INTERESTS: dict[str, list[str]] = {
    "paris":  _PARIS_DEFAULT_INTERESTS,
    "london": _LONDON_DEFAULT_INTERESTS,
}


def generate_city_interests(city_config: dict,
                             api_key: str = None,
                             model: str = "claude-sonnet-4-6",
                             n: int = 10) -> list[str]:
    """
    Return N city-specific visitor interest labels.
    Represents WHY people visit this city - not generic travel activities.
    Used to populate the Cat 6 interest menu in task generation prompts.

    Returns hardcoded list for Paris/London.
    Makes an LLM call for other cities if api_key is provided.
    Caches result in city_config["visitor_interests"].
    """
    city = city_config.get("city", "").lower()

    if city_config.get("visitor_interests"):
        return city_config["visitor_interests"]

    interests = _CITY_DEFAULT_INTERESTS.get(city, [])[:n]
    if interests:
        city_config["visitor_interests"] = interests
        return interests

    if not api_key:
        generic = [
            f"{city_config.get('display_name', city)} sights", "Local cuisine",
            "History", "Art & culture", "Architecture", "Parks & outdoor",
            "Shopping", "Music & nightlife", "Photography", "Local neighbourhoods",
        ][:n]
        city_config["visitor_interests"] = generic
        return generic

    try:
        from anthropic import Anthropic as _Anthropic
        client = _Anthropic(api_key=api_key)
        example = ('["Impressionist art", "Haussmann architecture", "French gastronomy", '
                   '"Wine culture", "Fashion", "History", "Canal walks", '
                   '"Photography", "Literary culture", "Contemporary galleries"]')
        prompt = (
            f"List exactly {n} broad visitor interests for {city_config['display_name']}, "
            f"{city_config['country']}. WHY tourists visit this specific city. "
            f"2-5 words each. Example for Paris: {example}. "
            f"Return {n} items for {city_config['display_name']}."
        )
        resp = client.messages.create(
            model=model, max_tokens=500,
            system="Return only a valid JSON array of strings. No markdown.",
            messages=[{"role": "user", "content": prompt}]
        )
        raw = resp.content[0].text.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        interests = json.loads(raw)
        if isinstance(interests, list) and len(interests) >= n:
            interests = interests[:n]
            city_config["visitor_interests"] = interests
            return interests
    except Exception as e:
        print(f"  ⚠ Interest generation failed ({e}), using generic fallback")

    generic = [
        f"{city_config.get('display_name', city)} sights", "Local cuisine",
        "History", "Art & culture", "Architecture", "Parks & outdoor",
        "Shopping", "Music & nightlife", "Photography", "Local neighbourhoods",
    ][:n]
    city_config["visitor_interests"] = generic
    return generic


def _generate_stub_briefs(city_config: dict, n_venues: int = 50) -> list[dict]:
    """Generate deterministic stub venue briefs from city config. Scales with n_venues."""
    districts = city_config["districts"]
    cuisines = city_config["cuisine_variety"]
    local = city_config["local_cuisine_label"]

    briefs = []

    # Scale tier pool and wrong_info count with n_venues
    _n_high = max(3, round(n_venues * 0.26))
    _n_mid  = max(5, round(n_venues * 0.42))
    _n_low  = n_venues - _n_high - _n_mid
    _n_wi   = max(2, round(n_venues * 0.40))  # W1: raised from 0.24
    tier_pool = (
        ["high"] * _n_high +
        ["mid"]  * _n_mid  +
        ["low"]  * _n_low
    )

    # Wrong info: only mid/low are candidates; take first _n_wi of them
    mid_low_indices = [i for i, t in enumerate(tier_pool) if t in ("mid", "low")]
    wrong_info_indices = set(mid_low_indices[:_n_wi])

    idx = 0
    dist_cycle = districts * max(6, n_venues // 8 + 1)  # enough to cover n_venues

    # ── Food/drink (25) ──────────────────────────────────────────────────────
    # Restaurants (10)
    cuisine_iter = iter(cuisines * 3)
    for i in range(10):
        cuisine = next(cuisine_iter) if i >= 2 else local
        briefs.append({
            "name": f"Stub Restaurant {i+1} ({cuisine.title()})",
            "category": "restaurant",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": idx in wrong_info_indices,
            "character": (f"A {cuisine} restaurant in {dist_cycle[idx % len(dist_cycle)]} "
                          f"serving traditional dishes in a "
                          f"{'cozy' if i % 2 == 0 else 'lively'} setting.")
        })
        idx += 1

    # Cafes (10 - up from 5 to balance 25)
    for i in range(10):
        briefs.append({
            "name": f"Stub Cafe {i+1}",
            "category": "cafe",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": idx in wrong_info_indices,
            "character": (f"An independent cafe in {dist_cycle[idx % len(dist_cycle)]} "
                          f"with good coffee and a quiet atmosphere.")
        })
        idx += 1

    # Bars (5)
    for i in range(5):
        briefs.append({
            "name": f"Stub Bar {i+1}",
            "category": "bar",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": idx in wrong_info_indices,
            "character": (f"A cocktail bar in {dist_cycle[idx % len(dist_cycle)]} "
                          f"with a late-night crowd and creative drinks menu.")
        })
        idx += 1

    # ── Sights/attractions (25) ──────────────────────────────────────────────
    # Museums (7)
    for i in range(7):
        briefs.append({
            "name": f"Stub Museum {i+1}",
            "category": "museum",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": idx in wrong_info_indices,
            "character": (f"A museum in {dist_cycle[idx % len(dist_cycle)]} "
                          f"with rotating exhibitions and a permanent collection.")
        })
        idx += 1

    # Attractions (10 - up from 6)
    for i in range(10):
        briefs.append({
            "name": f"Stub Attraction {i+1}",
            "category": "attraction",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": idx in wrong_info_indices,
            "character": (f"A popular attraction in {dist_cycle[idx % len(dist_cycle)]} "
                          f"visited by locals and tourists alike.")
        })
        idx += 1

    # Parks (5 - up from 4)
    for i in range(5):
        briefs.append({
            "name": f"Stub Park {i+1}",
            "category": "park",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": tier_pool[idx],
            "has_wrong_info": False,  # parks rarely have wrong info
            "character": (f"A public park in {dist_cycle[idx % len(dist_cycle)]} "
                          f"popular for walks and picnics.")
        })
        idx += 1

    # Neighbourhood (3)
    for i in range(3):
        briefs.append({
            "name": f"Stub Neighbourhood Walk {i+1}",
            "category": "neighbourhood",
            "district": dist_cycle[idx % len(dist_cycle)],
            "traffic_tier": "low",
            "has_wrong_info": False,
            "character": (f"A self-guided neighbourhood walk through "
                          f"{dist_cycle[idx % len(dist_cycle)]} with independent shops and cafes.")
        })
        idx += 1

    assert len(briefs) == 50, f"Stub generator produced {len(briefs)} briefs, expected 50"
    return briefs


# ─────────────────────────────────────────────────────────────────────────────
# DEDUP BRIEFS
# ─────────────────────────────────────────────────────────────────────────────

def _dedup_briefs(briefs: list[dict]) -> list[dict]:
    """
    Remove near-duplicate venue briefs from the plan_venues output.

    Two briefs are considered duplicates when ALL three conditions hold:
      1. Jaccard similarity of word tokens >= 0.75
      2. Same category
      3. Same district

    The longer (more complete) name is kept; the shorter is dropped.
    Operates in O(n²) but n is always ≤ ~100 so this is negligible.
    """
    import re as _re

    def _norm(name: str) -> set:
        # Strip apostrophes and hyphens first (they join parts of a word, not separate them)
        # then replace remaining punctuation with spaces for tokenisation
        s = _re.sub(r"['\-]", "", name.lower())
        s = _re.sub(r"[^\w\s]", " ", s)
        return set(s.split())

    to_remove: set[int] = set()

    for i, ba in enumerate(briefs):
        if i in to_remove:
            continue
        for j in range(i + 1, len(briefs)):
            if j in to_remove:
                continue
            bb = briefs[j]
            if ba.get("category") != bb.get("category"):
                continue
            if ba.get("district") != bb.get("district"):
                continue
            ta, tb = _norm(ba["name"]), _norm(bb["name"])
            if not ta or not tb:
                continue
            jaccard = len(ta & tb) / len(ta | tb)
            if jaccard >= 0.75:
                # Keep the longer name (more descriptive); drop the shorter
                keep, drop = (i, j) if len(ba["name"]) >= len(bb["name"]) else (j, i)
                to_remove.add(drop)
                print(f"  [dedup] Removed '{briefs[drop]['name']}' "
                      f"(duplicate of '{briefs[keep]['name']}', "
                      f"score={jaccard:.2f}, "
                      f"cat={ba['category']}, dist={ba['district']})")

    if to_remove:
        cleaned = [b for i, b in enumerate(briefs) if i not in to_remove]
        print(f"  [dedup] {len(to_remove)} duplicate(s) removed "
              f"({len(briefs)} → {len(cleaned)} briefs)")
        return cleaned
    return briefs


# ─────────────────────────────────────────────────────────────────────────────
# PLAN VENUES
# ─────────────────────────────────────────────────────────────────────────────

def plan_venues(city_config: dict, window: dict = None,
                api_key: str = None,
                model: str = "claude-sonnet-4-6",
                dry_run: bool = False,
                n_venues: int = 50) -> tuple[list[dict], list[dict]]:
    """
    Generate 50 venue briefs (and 5-8 event briefs if a window is provided).

    When window is given: calls _plan_prompt_with_events() - one LLM call
    returns both venues and events together, so events are semantically
    coherent with the venue pool from the start.

    Returns:
        (venue_briefs, event_briefs)
        venue_briefs: list of 50 venue dicts
        event_briefs: list of event dicts (empty if no window)
            Each event has venue_index (into venue_briefs), to be resolved
            to venue_id after the venues are written to DB.
    """
    if dry_run or not api_key:
        print("  Using stub venue plan (no API call)")
        return _generate_stub_briefs(city_config, n_venues=n_venues), []

    print("  Planning venue mix with LLM (real-venue-first)...")
    try:
        from anthropic import Anthropic as _Anthropic
    except ImportError:
        raise ImportError("anthropic package required: pip install anthropic")

    client = _Anthropic(api_key=api_key)
    # Events are generated separately at step 4 (generate_events_for_windows).
    # Window is still passed for seasonal context in the venue prompt, but
    # include_events=False avoids generating events that would be discarded.
    prompt = _plan_prompt_with_events(city_config, window=window, include_events=False, n_venues=n_venues)

    def _call_once(max_tok):
        resp = client.messages.create(
            model=model,
            max_tokens=max_tok,
            system="You are a helpful data generation assistant. Return only valid complete JSON, no truncation.",
            messages=[{"role": "user", "content": prompt}]
        )
        r = resp.content[0].text.strip()
        r = re.sub(r'```(?:json)?\s*', '', r)
        r = re.sub(r'```', '', r).strip()
        return r

    raw = ""
    for max_tok in [12000, 16000, 20000, 24000]:
        raw = _call_once(max_tok)
        if not raw:
            continue
        try:
            parsed = json.loads(raw)
            break
        except json.JSONDecodeError as e:
            print(f"  ⚠ JSON parse failed at {max_tok} tokens ({e}) - retrying...")
            continue
    else:
        raise ValueError(f"Could not get valid JSON from LLM. Last output:\n{raw[:500]}")

    # Extract venues from response (events generated separately at step 4)
    if isinstance(parsed, dict) and "venues" in parsed:
        briefs = parsed.get("venues", [])
    elif isinstance(parsed, list):
        briefs = parsed
    else:
        briefs = []
    event_briefs = []  # events handled by generate_events_for_windows

    # Deduplicate briefs before count validation
    briefs = _dedup_briefs(briefs)

    # Validate + normalise venue count
    if len(briefs) != n_venues:
        print(f"  ⚠ LLM returned {len(briefs)} briefs (expected {n_venues}) - padding/trimming")
        if len(briefs) > n_venues:
            # Tier-aware selection: keep ALL high-traffic venues (iconic landmarks
            # are always worth including), then fill mid/low at their FULL quotas.
            # Total may exceed n_venues — that's intentional.
            high_briefs = [b for b in briefs if b.get("traffic_tier") == "high"]
            non_high    = [b for b in briefs if b.get("traffic_tier") != "high"]

            # Mid/low get their original quotas (not squeezed by extra highs)
            _n_mid_t    = max(5, round(n_venues * 0.42))
            _n_low_t    = n_venues - max(3, round(n_venues * 0.26)) - _n_mid_t

            kept = list(high_briefs)
            tier_counts = {"mid": 0, "low": 0}
            tier_caps   = {"mid": _n_mid_t, "low": _n_low_t}
            overflow    = []

            for b in non_high:
                t = b.get("traffic_tier", "mid")
                if tier_counts.get(t, 0) < tier_caps.get(t, 0):
                    kept.append(b)
                    tier_counts[t] = tier_counts.get(t, 0) + 1
                else:
                    overflow.append(b)

            # If any tier under-produced, fill from overflow
            for tier in ["mid", "low"]:
                shortfall = tier_caps[tier] - tier_counts[tier]
                if shortfall > 0:
                    tier_overflow = [b for b in overflow if b.get("traffic_tier") == tier]
                    kept.extend(tier_overflow[:shortfall])
                    overflow = [b for b in overflow if b not in tier_overflow[:shortfall]]

            briefs = kept
            print(f"  Tier-aware selection: {len(high_briefs)} high (all kept) + "
                  f"{tier_counts['mid']} mid + {tier_counts['low']} low = {len(briefs)} total")
        else:
            stub_extras = _generate_stub_briefs(city_config, n_venues=n_venues)[len(briefs):]
            briefs += stub_extras[:n_venues - len(briefs)]

    # Enforce food/sight pool balance scaled to n_venues
    FOOD_CATS  = {"restaurant", "cafe", "bar"}
    SIGHT_CATS = {"museum", "attraction", "park", "neighbourhood"}
    food   = [b for b in briefs if b["category"] in FOOD_CATS]
    sights = [b for b in briefs if b["category"] in SIGHT_CATS]
    _n_food   = n_venues // 2
    _n_sights = n_venues - _n_food

    if len(food) != _n_food or len(sights) != _n_sights:
        print(f"  ⚠ Pool imbalance: {len(food)} food / {len(sights)} sights - rebalancing")
        while len(food) > _n_food:
            b = food.pop(); b["category"] = "attraction"; sights.append(b)
        while len(sights) > _n_sights:
            b = sights.pop(); b["category"] = "restaurant"; food.append(b)
        briefs = food + sights

    # Validate event_briefs - remove any with out-of-range venue_index
    valid_events = []
    for ev in event_briefs:
        idx = ev.get("venue_index")
        if isinstance(idx, int) and 0 <= idx < len(briefs):
            valid_events.append(ev)
        else:
            print(f"  ⚠ Event '{ev.get('name','?')}' has invalid venue_index {idx} - skipped")
    event_briefs = valid_events

    print(f"  [x] Venue plan ready: {len(briefs)} briefs ({len(event_briefs)} events planned)")
    return briefs, event_briefs





def write_planned_events(event_briefs: list[dict],
                          venue_id_map: dict[int, str],
                          city: str,
                          window_id: str,
                          window_dates: list[str],
                          db_path=None) -> int:
    """
    Write event briefs to the events table after venues have been saved to DB.

    venue_id_map: {venue_index: venue_id} - built after venue DB writes complete.
    Also writes sold_out_dates into ticket_availability for per-date sold-out traps.

    Returns number of events written.
    """
    from scripts.generation.db import get_connection, get_city_db_path
    conn = get_connection(db_path or get_city_db_path(city))
    written = 0

    for ev in event_briefs:
        idx    = ev.get("venue_index")
        vid    = venue_id_map.get(idx)
        if not vid:
            continue

        # Write event row
        try:
            conn.execute("""
                INSERT INTO events
                  (venue_id, city, window_id, name, description,
                   start_date, end_date, affects_hours, affects_access,
                   sold_out, modified_hours, price_local)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
            """, (
                vid, city, window_id,
                ev.get("name", "Special Event"),
                ev.get("description", ""),
                ev.get("start_date", window_dates[0] if window_dates else ""),
                ev.get("end_date",   window_dates[-1] if window_dates else ""),
                1 if ev.get("affects_hours") else 0,
                1 if ev.get("affects_access") else 0,
                1 if ev.get("sold_out") else 0,
                ev.get("modified_hours"),
                ev.get("price_local"),
            ))
            written += 1
        except Exception as e:
            print(f"  ⚠ Failed to write event '{ev.get('name')}': {e}")
            continue

        # Write sold_out_dates into ticket_availability
        for date_str in ev.get("sold_out_dates", []):
            if date_str not in window_dates:
                continue
            try:
                conn.execute("""
                    INSERT OR REPLACE INTO ticket_availability
                      (venue_id, date, status, sold_out, notes)
                    VALUES (?, ?, 'sold_out', 1, ?)
                """, (vid, date_str, f"Sold out - {ev.get('name', 'event')}"))
            except Exception:
                pass

    conn.commit()
    conn.close()
    print(f"  [x] {written}/{len(event_briefs)} events written to DB")
    return written



# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 - EVENT GENERATION (separate from venue planning)
# ─────────────────────────────────────────────────────────────────────────────

_EVENT_GEN_PROMPT = """You are designing the event calendar for TravelBench, a travel planning benchmark.

CITY: {display_name}, {country}
VENUE POOL ({n_venues} venues):
{venue_list}

WINDOWS ({n_windows} windows):
{window_list}

VISITOR INTERESTS: {interests}

YOUR TASK: design events across ALL windows. Events are the engine of benchmark
difficulty - planning agents must call get_official_site(venue_id, date) to
discover them. Design each event to create a genuine planning challenge.

MANDATORY PER WINDOW:
  4-8 events total per window (not per venue - per window)
  >=1 event with affects_access=true (advance booking required - F-score trap)
  >=1 event with affects_hours=true (changed opening times)
  >=1 sold_out_dates entry on an anchor date - agents who do not check official
    site with the anchor date will book a sold-out venue
  Events span >=3 different venue categories per window

HARD CONSTRAINTS:
  No sold_out or affects_access events at high-traffic venues
    (high-traffic venue indices: {high_traffic_indices})
  Max 2 events per venue across ALL windows combined
  All event dates must fall within that window's dates array

source_hint: write a short, natural-language planning tip (15-30 words) that a
  venue's official site might display, e.g. "Book at least 2 weeks ahead - this
  exhibition sells out on anchor dates." Used verbatim in source docs.

task_hook options:
  "type6" -> event creates window-specific conflict (holiday closure + special access)
  "type5" -> event narrows an already-tight feasibility set
  "type2" -> event changes hours in ways that affect subset-selection tasks
  "general" -> doc_appeared B-score trigger: agent rewarded for proactively checking

Return ONLY a flat JSON array of event objects:
[
  {{
    "venue_index":    <int>,
    "window_id":      "<window_id>",
    "name":           "<event name>",
    "description":    "<1-2 sentences: what it is, why it matters for planning>",
    "start_date":     "YYYY-MM-DD",
    "end_date":       "YYYY-MM-DD",
    "affects_hours":  true,
    "modified_hours": "<e.g. '10:00-22:00 Thu-Sat' or null>",
    "affects_access": false,
    "sold_out":       false,
    "sold_out_dates": ["YYYY-MM-DD"],
    "price_local":      18.0,
    "task_hook":      "type6",
    "source_hint":    "<planning tip>"
  }}
]"""


def _build_venue_list_for_events(briefs: list[dict]) -> tuple[str, list[int]]:
    """Format venue pool for the event generation prompt. Returns (text, high_traffic_indices)."""
    lines = []
    high_indices = []
    for i, b in enumerate(briefs):
        tier = b.get("traffic_tier", "mid")
        if tier == "high":
            high_indices.append(i)
        lines.append(
            f"  [{i:2d}] {b['name']} ({b['category']}, {b['district']}, {tier})"
            f" - {b.get('character', '')}"
        )
    return "\n".join(lines), high_indices


def _build_window_list_for_events(windows: list[dict]) -> str:
    """Format windows for the event generation prompt."""
    lines = []
    for w in windows:
        anchor_str = ", ".join(
            f"{e['name']} ({e['date']})" for e in w.get("anchor_events", [])
        )
        lines.append(
            f"  {w['window_id']}: {w['label']}  |  "
            f"{w['dates'][0]}–{w['dates'][-1]}  |  "
            f"Anchors: {anchor_str}"
        )
    return "\n".join(lines)


def _validate_events(events: list, windows: list[dict],
                     n_venues: int, high_indices: list[int]) -> list[str]:
    """Validate event list against all E1 constraints. Returns error strings (empty = ok)."""
    errors = []
    window_map = {w["window_id"]: w for w in windows}
    all_dates_by_window = {w["window_id"]: set(w["dates"]) for w in windows}

    events_by_window: dict[str, list] = {w["window_id"]: [] for w in windows}
    venue_event_count: dict[int, int] = {}

    for i, ev in enumerate(events):
        wid = ev.get("window_id", "")
        vidx = ev.get("venue_index")

        if wid not in window_map:
            errors.append(f"event[{i}] '{ev.get('name')}': unknown window_id '{wid}'")
            continue
        if not isinstance(vidx, int) or not (0 <= vidx < n_venues):
            errors.append(f"event[{i}] '{ev.get('name')}': venue_index {vidx} out of range [0,{n_venues})")
            continue

        events_by_window[wid].append(ev)
        venue_event_count[vidx] = venue_event_count.get(vidx, 0) + 1

        # Dates within window
        window_dates = all_dates_by_window[wid]
        for d in [ev.get("start_date"), ev.get("end_date")]:
            if d and d not in window_dates:
                errors.append(f"event[{i}] '{ev.get('name')}': date {d} outside window {wid}")
        for d in ev.get("sold_out_dates", []):
            if d not in window_dates:
                errors.append(f"event[{i}] '{ev.get('name')}': sold_out_date {d} outside window {wid}")

        # No sold_out / affects_access on high-traffic venues
        if vidx in high_indices:
            if ev.get("sold_out") or ev.get("sold_out_dates"):
                errors.append(f"event[{i}]: sold_out on high-traffic venue [{vidx}]")
            if ev.get("affects_access"):
                errors.append(f"event[{i}]: affects_access on high-traffic venue [{vidx}]")

    # Per-window checks
    for wid, wevents in events_by_window.items():
        w = window_map[wid]
        anchor_dates = {e["date"] for e in w.get("anchor_events", [])}

        if not (4 <= len(wevents) <= 8):
            errors.append(f"window {wid}: need 4-8 events, got {len(wevents)}")
        if not any(ev.get("affects_access") for ev in wevents):
            errors.append(f"window {wid}: need >=1 affects_access event")
        if not any(ev.get("affects_hours") for ev in wevents):
            errors.append(f"window {wid}: need >=1 affects_hours event")

        has_anchor_soldout = any(
            d in anchor_dates
            for ev in wevents
            for d in ev.get("sold_out_dates", [])
        )
        if not has_anchor_soldout:
            errors.append(f"window {wid}: need >=1 sold_out_date on an anchor date")

        cats_in_window = {
            ev.get("_category", "") for ev in wevents if ev.get("_category")
        }
        if cats_in_window and len(cats_in_window) < 3:
            errors.append(
                f"window {wid}: events span only {len(cats_in_window)} categories (need >=3)"
            )

    # Per-venue max 2 events
    for vidx, count in venue_event_count.items():
        if count > 2:
            errors.append(f"venue[{vidx}]: has {count} events across all windows (max 2)")

    return errors


def generate_events_for_windows(city_config: dict,
                                  windows: list[dict],
                                  venue_briefs: list[dict],
                                  city_interests: list[str],
                                  api_key: str,
                                  model: str = "claude-sonnet-4-6") -> list[dict]:
    """
    Generate events for ALL windows in a single LLM call.

    Runs AFTER venue briefs are confirmed (post-enrich), so events are assigned
    to real venues with known categories. This is separate from plan_venues -
    the plan_venues path still produces events-as-side-effect for the first window
    only, but this function is the canonical Step 4 for the full pipeline.

    Returns a flat list of event dicts, each with venue_index and window_id.
    The orchestrator converts this to events_by_venue: dict[int, list[dict]]
    before passing to _generate_one.

    On LLM failure returns [] - events are additive, pipeline continues.
    """
    if not api_key or not windows or not venue_briefs:
        return []

    venue_list, high_indices = _build_venue_list_for_events(venue_briefs)
    window_list = _build_window_list_for_events(windows)
    interests_str = ", ".join(city_interests[:10]) if city_interests else "general tourism"

    prompt = _EVENT_GEN_PROMPT.format(
        display_name=city_config.get("display_name", ""),
        country=city_config.get("country", ""),
        n_venues=len(venue_briefs),
        venue_list=venue_list,
        n_windows=len(windows),
        window_list=window_list,
        interests=interests_str,
        high_traffic_indices=high_indices,
    )

    try:
        from anthropic import Anthropic as _Anthropic
    except ImportError:
        print("  ⚠ anthropic package not available - skipping event generation")
        return []

    client = _Anthropic(api_key=api_key)
    events = None
    last_error = ""

    for attempt in range(3):
        try:
            resp = client.messages.create(
                model=model,
                max_tokens=6000,
                system="Return only a valid JSON array. No markdown, no explanation.",
                messages=[{"role": "user", "content": prompt}]
            )
            raw = resp.content[0].text.strip()
            raw = re.sub(r'```(?:json)?\s*', '', raw)
            raw = re.sub(r'```', '', raw).strip()
            candidate = json.loads(raw)
            if not isinstance(candidate, list):
                raise ValueError("expected JSON array")

            # Inject _category for validation
            for ev in candidate:
                vidx = ev.get("venue_index")
                if isinstance(vidx, int) and 0 <= vidx < len(venue_briefs):
                    ev["_category"] = venue_briefs[vidx].get("category", "")

            errs = _validate_events(candidate, windows, len(venue_briefs), high_indices)
            if errs:
                last_error = f"validation: {errs[:3]}"
                print(f"  ⚠ Event gen attempt {attempt+1} validation errors: {errs[:3]}")
                # Auto-fix: drop events with structural errors (bad window / out-of-range index)
                known_wids = {w["window_id"] for w in windows}
                candidate = [
                    ev for ev in candidate
                    if ev.get("window_id") in known_wids
                    and isinstance(ev.get("venue_index"), int)
                    and 0 <= ev["venue_index"] < len(venue_briefs)
                ]
                errs2 = _validate_events(candidate, windows, len(venue_briefs), high_indices)
                if not errs2:
                    events = candidate
                    break
                last_error = f"post-fix: {errs2[:3]}"
            else:
                events = candidate
                break
        except Exception as e:
            last_error = str(e)
            print(f"  ⚠ Event gen attempt {attempt+1} error: {e}")

    if events is None:
        print(f"  ⚠ Event generation failed ({last_error}) - continuing without events")
        return []

    # Remove internal _category field before returning
    for ev in events:
        ev.pop("_category", None)

    by_window = {}
    for ev in events:
        by_window.setdefault(ev["window_id"], []).append(ev)
    summary = ", ".join(f"{wid}: {len(evs)}" for wid, evs in by_window.items())
    print(f"  [x] {len(events)} events generated ({summary})")
    return events

def build_event_prompt_block(event_briefs: list[dict],
                              venue_briefs: list[dict],
                              window_dates: list[str]) -> str:
    """
    Build the ACTIVE EVENTS block injected into the task generation prompt.
    Called after plan_venues() returns event_briefs, before venue DB writes
    (venue_index still valid at this point).

    Returns a formatted string ready to inject into build_typed_task_prompt.
    """
    if not event_briefs:
        return ""

    lines = ["ACTIVE EVENTS DURING THIS WINDOW:"]
    lines.append("These events are confirmed - task generation agents should know about them.")
    lines.append("Build Type 6, Type 5, or Type 2 tasks that interact with these events.")
    lines.append("")

    for ev in event_briefs:
        idx   = ev.get("venue_index", "?")
        vname = venue_briefs[idx]["name"] if isinstance(idx, int) and idx < len(venue_briefs) else "?"
        vcat  = venue_briefs[idx]["category"] if isinstance(idx, int) and idx < len(venue_briefs) else "?"

        sold_dates = ev.get("sold_out_dates", [])
        access_str = "booking required" if ev.get("affects_access") else "walk-in"
        hours_str  = f"Hours: {ev['modified_hours']}" if ev.get("modified_hours") else ""
        sold_str   = f"SOLD OUT on: {', '.join(sold_dates)}" if sold_dates else ""
        price_str  = f"Price: ${ev['price_local']:.0f}" if ev.get("price_local") else "free"

        details = " | ".join(filter(None, [hours_str, price_str, access_str, sold_str]))

        lines.append(f"  [{idx}] {vname} ({vcat}) - {ev.get('name', '?')}")
        lines.append(f"      {ev.get('start_date','')} to {ev.get('end_date','')}")
        lines.append(f"      {details}")
        lines.append(f"      {ev.get('description', '')}")
        lines.append(f"      Best for: {ev.get('task_hook', 'general')}")
        lines.append("")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# DISPATCH SINGLE VENUE
# ─────────────────────────────────────────────────────────────────────────────

def _generate_one(brief: dict, city: str, api_key: str,
                  model: str, db_path: Path, verbose: bool) -> dict:
    """Worker function for parallel dispatch."""
    import time as _time
    from pathlib import Path as _Path
    log_dir = db_path.parent.parent / "logs" / "venue_runs"
    log_dir.mkdir(parents=True, exist_ok=True)
    safe_name = brief["name"].replace(" ", "_").replace("/", "_")[:30]
    log_path = log_dir / f"{safe_name}_{int(_time.time())}.json"

    result = run_venue_agent(
        city=city,
        category=brief["category"],
        district=brief["district"],
        traffic_tier=brief["traffic_tier"],
        name=brief["name"],
        archetype=brief.get("character"),
        has_wrong_info=brief.get("has_wrong_info", False),
        recommended_pace=brief.get("recommended_pace"),
        coverage_tags=brief.get("coverage_tags", []),
        overpass_ref=brief.get("overpass_ref"),
        event_briefs=brief.get("event_briefs", []),
        regulation_directives=brief.get("regulation_directives"),
        api_key=api_key,
        model=model,
        db_path=db_path,
        log_path=log_path,
    )
    result["brief_name"] = brief["name"]
    result["has_wrong_info"] = brief.get("has_wrong_info", False)
    return result


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ORCHESTRATOR
# ─────────────────────────────────────────────────────────────────────────────

def generate_city_venues(city: str,
                         api_key: str = None,
                         anthropic_key: str = None,
                         model: str = "deepseek-chat",
                         planning_model: str = None,
                         db_path: Path = None,
                         dry_run: bool = False,
                         workers: int = 5,
                         verbose: bool = False,
                         limit: int = None,
                         wrong_info_only: bool = False,
                         window_id: str = None,
                         ors_key: str = None,
                         skip_matrix: bool = False,
                         skip_tickets: bool = False,
                         skip_venue_difficulty: bool = False) -> dict:
    """
    Full orchestration: research city -> plan venues -> generate all -> validate.

    Events are generated per seasonal window:
    - If window_id is given: generate events for that specific window only.
    - If window_id is None (default): generate events for ALL windows of the city.
      The venue pool is generated once and shared; events are window-specific.

    Returns summary dict with counts, issues, and events_written count.
    """
    if db_path is None:
        db_path = get_city_db_path(city)
    print(f"\n🏙  Generating venue pool for {city.title()}...")

    # ── Step 1: Ensure city config exists ────────────────────────────────────
    print("\n[1/4] City config...")
    # research_city uses DeepSeek (OpenAI-compatible), always deepseek-chat
    # plan_venues uses Anthropic; --planning-model controls that model
    _research_model  = "deepseek-chat"
    _planning_model  = planning_model or "claude-sonnet-4-6"
    city_config = research_city(
        city_name=city, api_key=api_key, model=_research_model,
        db_path=db_path, dry_run=dry_run
    )

    city_key = city.lower().replace(" ", "_")
    conn = get_connection(db_path)
    db_row = conn.execute(
        "SELECT * FROM city_config WHERE city = ?", (city_key,)
    ).fetchone()
    conn.close()
    if db_row:
        city_config = dict(db_row)
        # Unpack JSON columns
        for col in ("districts", "cuisine_variety", "task_dates"):
            if isinstance(city_config.get(col), str):
                city_config[col] = json.loads(city_config[col] or "[]")

    # Backfill from stub if any list fields are empty (older DB rows)
    if city_key in STUB_CONFIGS:
        stub = STUB_CONFIGS[city_key]
        if not city_config.get("districts"):
            city_config["districts"] = stub.get("districts", [])
        if not city_config.get("cuisine_variety"):
            city_config["cuisine_variety"] = stub.get("cuisine_variety", [])

    # ── Step 2: Ensure windows exist ─────────────────────────────────────────
    # For known cities (london/hokkaido/rio): populate_windows writes hardcoded defs.
    # For new cities: generate_and_store_windows calls LLM. Skip if already populated.
    from scripts.generation.populate_seasonal_windows import (
        populate_windows as _pop_windows,
        get_windows as _get_windows,
        generate_and_store_windows as _gen_windows,
    )
    _existing_windows = _get_windows(city_key, db_path=db_path)
    if not _existing_windows:
        print(f"\n[2/5] Window generation...")
        _pop_result = _pop_windows(city_key, db_path=db_path)
        if _pop_result["status"] == "unknown_city":
            if not dry_run:
                # Live run: use LLM (falls back to stub if no key or LLM fails)
                _gen_result = _gen_windows(
                    city_key, city_config,
                    api_key=anthropic_key,
                    model=_planning_model,
                    db_path=db_path,
                )
                if _gen_result["status"] in ("ok", "stub"):
                    label = "" if _gen_result["status"] == "ok" else " (stub fallback)"
                    print(f"  [x] {_gen_result['windows_written']} windows generated{label}")
                else:
                    print(f"  ⚠ Window generation failed: {_gen_result.get('message','')}")
            else:
                # Dry-run: always write stub windows so downstream steps can proceed
                from scripts.generation.populate_seasonal_windows import _stub_windows as _sw
                _stub_wins = _sw(city_key, city_config)
                _conn_w = get_connection(db_path)
                _conn_w.execute(
                    "UPDATE city_config SET seasonal_windows = ? WHERE city = ?",
                    (json.dumps(_stub_wins), city_key)
                )
                _conn_w.commit()
                _conn_w.close()
                print(f"  [x] {len(_stub_wins)} stub windows written (dry-run)")
        elif _pop_result["status"] == "ok":
            print(f"  [x] {_pop_result['windows_written']} hardcoded windows loaded")
    else:
        print(f"\n[2/5] Windows: {len(_existing_windows)} already in DB - skipping")

    # ── Step 3: Plan venue mix ────────────────────────────────────────────────
    # Reload windows after Step 2 (may have just been generated)
    _all_windows = _get_windows(city_key, db_path=db_path) or []
    if window_id:
        _windows_to_process = [w for w in _all_windows if w["window_id"] == window_id]
        if not _windows_to_process:
            print(f"  ⚠ Window '{window_id}' not found in DB - running without events")
    else:
        _windows_to_process = _all_windows

    # Generate city interests BEFORE plan_venues so the planning prompt
    # has cultural context (visitor_interests) for venue selection.
    city_interests = generate_city_interests(city_config, api_key=anthropic_key, model=_planning_model)

    # Plan venues using first window for seasonal context (or no context if no windows)
    _planning_window = _windows_to_process[0] if _windows_to_process else None
    print(f"\n[3/5] Planning venue mix{' (window: ' + _planning_window['label'] + ')' if _planning_window else ''}...")
    briefs, _ = plan_venues(
        city_config=city_config,
        api_key=anthropic_key,
        model=_planning_model,
        dry_run=dry_run,
        window=_planning_window,
        n_venues=limit or 50,
    )

    # ── Post-process briefs: enforce pace and wrong_info by code ─────────────
    #
    # Pace: Design decision says agent uses category + booking_required +
    # recommended_visit_minutes as signals - editorial judgment, not mechanical.
    # However DeepSeek defaults everything to "moderate", so if no spread
    # is present we assign by code using the same signals at brief time.
    # (booking_required/visit_minutes aren't in briefs yet, so we use
    #  category + traffic_tier as proxies, matching the design intent.)
    #
    # Category-based pace logic (mirrors DESIGN_DECISIONS.md guidance):
    #   intense: major museums, ticketed attractions (high-traffic sights)
    #   relaxed: parks, neighbourhood walks, cafes (low-pressure venues)
    #   moderate: everything else (restaurants, bars, galleries, mid museums)

    PACE_INTENSE_CATS  = {"museum", "attraction"}
    PACE_RELAXED_CATS  = {"park", "neighbourhood", "cafe"}

    # Score each brief: intense beats relaxed; high-traffic museums = intense
    def _brief_pace(b: dict) -> str:
        cat  = b.get("category", "")
        tier = b.get("traffic_tier", "mid")
        if cat in PACE_INTENSE_CATS:
            return "intense"
        if cat in PACE_RELAXED_CATS:
            return "relaxed"
        # Bars at high-traffic = moderate-intense; restaurants = moderate
        if cat == "bar" and tier == "high":
            return "intense"
        return "moderate"

    pace_counts = {"relaxed": 0, "moderate": 0, "intense": 0}
    for b in briefs:
        p = b.get("recommended_pace")
        if p in pace_counts:
            pace_counts[p] += 1

    # Only override if LLM produced no spread (all moderate)
    all_moderate = pace_counts["relaxed"] == 0 and pace_counts["intense"] == 0
    if all_moderate:
        print("  ⚠ All briefs are 'moderate' - assigning pace from category+tier (design signals)")
        for b in briefs:
            if b.get("recommended_pace") not in ("relaxed", "intense"):
                b["recommended_pace"] = _brief_pace(b)
    else:
        # LLM assigned some spread - fill any nulls with category-based default
        for b in briefs:
            if b.get("recommended_pace") not in ("relaxed", "moderate", "intense"):
                b["recommended_pace"] = _brief_pace(b)

    # Wrong info: if LLM assigned fewer than _n_wi, assign by code from mid/low pool
    import random as _random
    _n_wi_target = max(2, round(len(briefs) * 0.40))  # W1: raised from 0.24
    _wi_actual   = sum(1 for b in briefs if b.get("has_wrong_info"))
    if _wi_actual < _n_wi_target:
        print(f"  ⚠ Only {_wi_actual}/{_n_wi_target} wrong_info briefs - assigning remainder by code")
        mid_low_unset = [b for b in briefs
                         if not b.get("has_wrong_info")
                         and b.get("traffic_tier") in ("mid", "low")]
        _random.shuffle(mid_low_unset)
        for b in mid_low_unset[:_n_wi_target - _wi_actual]:
            b["has_wrong_info"] = True

    # ── P2: Tier rebalancing - same pattern as wrong_info ────────────────────
    # LLM systematically skews high/mid; enforce low-tier target by code.
    from collections import Counter as _Counter
    _n_venues_actual = len(briefs)
    _n_high_tgt = max(3, round(_n_venues_actual * 0.26))
    _n_mid_tgt  = max(5, round(_n_venues_actual * 0.42))
    _n_low_tgt  = _n_venues_actual - _n_high_tgt - _n_mid_tgt
    _tier_actual = _Counter(b.get("traffic_tier", "mid") for b in briefs)
    _low_deficit = _n_low_tgt - _tier_actual.get("low", 0)
    if _low_deficit > 0:
        print(f"  ⚠ Only {_tier_actual.get('low',0)}/{_n_low_tgt} low-tier - downgrading {_low_deficit} mid venues")
        mid_candidates = sorted(
            [b for b in briefs if b.get("traffic_tier") == "mid"],
            key=lambda b: len(b.get("name", ""))
        )
        for b in mid_candidates[:_low_deficit]:
            b["traffic_tier"] = "low"

    # Print brief summary
    from collections import Counter
    cat_counts  = Counter(b["category"]         for b in briefs)
    tier_counts = Counter(b["traffic_tier"]      for b in briefs)
    pace_dist   = Counter(b.get("recommended_pace", "?") for b in briefs)
    wi_count    = sum(1 for b in briefs if b.get("has_wrong_info"))
    print(f"  Categories: {dict(cat_counts)}")
    print(f"  Tiers: {dict(tier_counts)}")
    print(f"  Pace: {dict(pace_dist)}")
    print(f"  Wrong info planned: {wi_count}")

    # ── Step 3b: Enrich with Overpass data ───────────────────────────────────
    print("\n[3b/5] Enriching with Overpass (real venue coordinates)...")
    briefs = enrich_briefs(briefs, city_config, dry_run=dry_run)

    if wrong_info_only:
        original_count = len(briefs)
        briefs = [b for b in briefs if b.get("has_wrong_info") and b.get("traffic_tier") in ("mid", "low")]
        print(f"  ⚠ --wrong-info-only: {len(briefs)} of {original_count} briefs have wrong info (mid/low tier)")

    if limit is not None and len(briefs) > limit:
        # Tier-aware selection in plan_venues already handled trimming.
        # Only warn — don't re-truncate, as that would squeeze out low-tier venues.
        n_high = sum(1 for b in briefs if b.get("traffic_tier") == "high")
        print(f"  ℹ {len(briefs)} briefs after tier-aware selection "
              f"(requested {limit}, {n_high} high-traffic kept)")

    # ── Step 4: Generate events for all windows ───────────────────────────────
    # Runs BEFORE venue agents so each venue receives its assigned events.
    # city_interests already generated before plan_venues (Step 3).
    all_events: list[dict] = []

    if _windows_to_process and not dry_run and anthropic_key:
        print(f"\n[4/5] Generating events for {len(_windows_to_process)} window(s)...")
        all_events = generate_events_for_windows(
            city_config=city_config,
            windows=_windows_to_process,
            venue_briefs=briefs,
            city_interests=city_interests,
            api_key=anthropic_key,
            model=_planning_model,
        )
    elif _windows_to_process:
        print("\n[4/5] Skipping event generation (dry-run or no API key)")
    else:
        print("\n[4/5] No windows - skipping event generation")

    # Build events_by_venue: venue_index -> [event, ...] for venue agent injection
    events_by_venue: dict[int, list[dict]] = {}
    for ev in all_events:
        idx = ev.get("venue_index")
        if isinstance(idx, int):
            events_by_venue.setdefault(idx, []).append(ev)

    # Attach event_briefs to each brief before parallel dispatch
    for i, brief in enumerate(briefs):
        brief["event_briefs"] = events_by_venue.get(i, [])

    # ── Step 5: Generate all venues — two-phase with regulation steering ─────
    total = len(briefs)
    PHASE1_SIZE = min(total // 2, 25)  # first half, capped at 25
    phase1_briefs = briefs[:PHASE1_SIZE]
    phase2_briefs = briefs[PHASE1_SIZE:]

    print(f"\n[5/5] Generating {total} venues ({workers} parallel workers)")
    print(f"  Phase 1: {len(phase1_briefs)} venues (no regulation steering)")
    print(f"  Phase 2: {len(phase2_briefs)} venues (with regulation steering if needed)")
    print(f"  Logs -> logs/venue_runs/")
    successes = []
    failures = []

    def _progress_line():
        done = len(successes) + len(failures)
        pct = done / total * 100
        bar_len = 30
        filled = int(bar_len * done / total)
        bar = "█" * filled + "░" * (bar_len - filled)
        fail_str = f"  {len(failures)} failed" if failures else ""
        print(f"\r  [{bar}] {done:2d}/{total} ({pct:5.1f}%){fail_str}", end="", flush=True)

    def _run_batch(batch):
        """Run a batch of briefs in parallel, append to successes/failures."""
        _progress_line()
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(
                    _generate_one, brief, city_key, api_key, model, db_path, verbose
                ): brief
                for brief in batch
            }
            for future in as_completed(futures):
                brief = futures[future]
                try:
                    result = future.result()
                    if result["status"] == "success":
                        successes.append(result)
                    else:
                        failures.append({"brief_name": brief["name"], **result})
                except Exception as e:
                    failures.append({"brief_name": brief["name"], "error": str(e)})
                _progress_line()

    # ── Phase 1: generate first batch without steering ────────────────────────
    _run_batch(phase1_briefs)

    # ── Checkpoint: compute regulation distribution from DB ───────────────────
    _REG_STEERING_FIELDS = [
        "wheelchair_accessible", "pet_friendly", "photography_allowed",
        "family_friendly", "reservation_required", "outside_food_allowed",
    ]
    _SKEW_THRESHOLD = 0.75  # if >75% on one side, steer toward minority

    reg_directives_for_phase2 = {}
    if phase2_briefs and not dry_run:
        try:
            _conn = get_connection(db_path)
            _verified = _conn.execute(
                "SELECT * FROM venues WHERE city=? AND page_status='verified'",
                (city_key,)
            ).fetchall()
            _conn.close()

            if len(_verified) >= 10:  # need enough data for meaningful distribution
                print(f"\n  [regulation checkpoint] {len(_verified)} venues committed")
                for reg in _REG_STEERING_FIELDS:
                    vals = [r[reg] for r in _verified if r[reg] is not None]
                    if not vals:
                        continue
                    true_pct = sum(1 for v in vals if v) / len(vals)
                    if true_pct > _SKEW_THRESHOLD:
                        reg_directives_for_phase2[reg] = (
                            0, f"currently {true_pct:.0%} true — need more false"
                        )
                        print(f"    ⚠ {reg}: {true_pct:.0%} true → steering phase 2 toward false")
                    elif true_pct < (1 - _SKEW_THRESHOLD):
                        reg_directives_for_phase2[reg] = (
                            1, f"currently {true_pct:.0%} true — need more true"
                        )
                        print(f"    ⚠ {reg}: {true_pct:.0%} true → steering phase 2 toward true")

                if not reg_directives_for_phase2:
                    print("    ✓ No regulation skew detected — phase 2 unsteered")
        except Exception as _e:
            print(f"  ⚠ Regulation checkpoint failed ({_e}) — phase 2 unsteered")

    # ── Phase 2: generate remaining venues with regulation directives ─────────
    if reg_directives_for_phase2:
        for brief in phase2_briefs:
            brief["regulation_directives"] = reg_directives_for_phase2

    _run_batch(phase2_briefs)

    print()  # newline after progress bar

    if failures:
        print(f"  [x] {len(successes)} succeeded  [ ] {len(failures)} failed:")
        for f in failures:
            print(f"    [ ] {f.get('brief_name','?')}: {f.get('message', f.get('error','?'))[:80]}")
    else:
        print(f"  [x] All {len(successes)} venues generated successfully")

    # ── Step 6: Validate ─────────────────────────────────────────────────────
    print("\n[6] Validating venue pool...")
    validation = validate_city(city_key, full=False, db_path=db_path)
    print_report(validation)

    # ── Step 7: Travel matrix ─────────────────────────────────────────────────
    matrix_pairs = 0
    if not skip_matrix:
        print("\n[7] Building travel matrix...")
        from scripts.generation.build_travel_matrix import build_travel_matrix
        matrix_result = build_travel_matrix(
            city=city_key,
            api_key=ors_key,
            db_path=db_path,
            dry_run=dry_run,
        )
        matrix_pairs = matrix_result.get("pairs", 0)
        method = matrix_result.get("method", "haversine")
        status = matrix_result.get("status", "?")
        if status in ("ok", "dry_run"):
            print(f"  [x] {matrix_pairs} pairs computed via {method}")
        elif status == "no_venues":
            print("  ⚠ No venues with coordinates - matrix skipped")
        else:
            print(f"  ⚠ Matrix status: {status}")
    else:
        print("\n[7] Travel matrix skipped (--skip-matrix)")

    # ── Step 8a: Ticket availability (probabilistic baseline) ─────────────────
    # Runs BEFORE event writing so that deterministic sold_out rows from
    # write_planned_events win via INSERT OR REPLACE over probabilistic rows.
    ticket_rows = 0
    if not skip_tickets:
        print("\n[8a] Populating ticket availability...")
        from scripts.generation.populate_ticket_availability import populate_ticket_availability
        ta_result = populate_ticket_availability(
            city=city_key,
            dry_run=dry_run,
            db_path=db_path,
        )
        ticket_rows = ta_result.get("rows", 0)
        ta_status = ta_result.get("status", "?")
        if ta_status == "ok":
            print(f"  [x] {ticket_rows} availability rows written "
                  f"({ta_result.get('sold_out', 0)} sold-out, "
                  f"{ta_result.get('limited', 0)} limited)")
        elif ta_status == "no_windows":
            print("  ⚠ No windows in DB - ticket availability skipped")
        elif ta_status == "no_bookable_venues":
            print("  ⚠ No booking_required venues - ticket availability skipped")
        else:
            print(f"  ⚠ Ticket availability status: {ta_status}")
    else:
        print("\n[8a] Ticket availability skipped (--skip-tickets)")

    # ── Step 8b: Write events to DB (deterministic sold_out overrides) ────────
    # Runs AFTER ticket availability so event-specific sold_out_dates
    # (the primary mechanism for type6 difficulty) override the probabilistic
    # rows written in 8a.
    total_events_written = 0
    windows_processed    = []

    if all_events and _windows_to_process:
        print(f"\n[8b] Writing {len(all_events)} events to DB...")

        _conn2 = get_connection(db_path)
        _venue_rows = _conn2.execute(
            "SELECT venue_id, name FROM venues WHERE city = ? AND page_status = 'verified'",
            (city_key,)
        ).fetchall()
        _conn2.close()

        _name_to_id = {r["name"]: r["venue_id"] for r in _venue_rows}
        venue_id_map = {
            i: _name_to_id.get(b["name"])
            for i, b in enumerate(briefs)
            if _name_to_id.get(b["name"])
        }

        # Log dropped events (venues that failed generation)
        _dropped = sum(1 for ev in all_events if not venue_id_map.get(ev.get("venue_index")))
        if _dropped:
            print(f"  ⚠ {_dropped} event(s) dropped — venue generation failed for those venues")

        events_by_window: dict[str, list] = {}
        for ev in all_events:
            events_by_window.setdefault(ev["window_id"], []).append(ev)

        for window in _windows_to_process:
            wid = window["window_id"]
            wevents = events_by_window.get(wid, [])
            if wevents:
                n = write_planned_events(
                    event_briefs=wevents,
                    venue_id_map=venue_id_map,
                    city=city_key,
                    window_id=wid,
                    window_dates=window.get("dates", []),
                    db_path=db_path,
                )
                total_events_written += n
                windows_processed.append(wid)
    elif _windows_to_process and not dry_run:
        print("\n  No events to write (generation skipped or returned empty)")

    # ── Step 9: Venue difficulty scores ───────────────────────────────────────
    venue_difficulty_count = 0
    if not skip_venue_difficulty:
        print("\n[9] Computing venue difficulty scores...")
        from scripts.generation.compute_venue_difficulty import compute_all_venue_difficulties
        difficulty_scores = compute_all_venue_difficulties(
            city=city_key,
            dry_run=dry_run,
            db_path=db_path,
        )
        venue_difficulty_count = len(difficulty_scores)
        if difficulty_scores:
            mean_score = sum(difficulty_scores.values()) / len(difficulty_scores)
            print(f"  [x] {venue_difficulty_count} venue difficulty scores computed "
                  f"(mean={mean_score:.3f})")
        else:
            print("  ⚠ No venues scored (no verified venues or source docs)")
    else:
        print("\n[9] Venue difficulty scores skipped (--skip-venue-difficulty)")

    # ── Step 10: Venue events (events table) ─────────────────────────────────
    events_written = 0
    if not dry_run:
        print("\n[10] Writing venue events to events table...")
        try:
            from scripts.generation.generate_events import generate_events as _gen_events
            ev_result = _gen_events(city_key, dry_run=False, db_path=db_path)
            events_written = ev_result.get("total_events", 0)
            sold_out_ev = ev_result.get("sold_out", 0)
            access_ev   = ev_result.get("affects_access", 0)
            if ev_result.get("status") == "ok":
                print(f"  [x] {events_written} events written "
                      f"({sold_out_ev} sold-out, {access_ev} affects-access)")
            else:
                print(f"  ⚠ Event generation status: {ev_result.get('status')}")
        except Exception as e:
            print(f"  ⚠ Event generation failed: {e}")
    else:
        print("\n[10] Venue events skipped (dry-run)")

    # ── Step 11: Venue window flags (geographic/seasonal annotations) ─────────
    flags_written = 0
    if not dry_run:
        print("\n[11] Annotating venues with window flags...")
        try:
            from scripts.generation.annotate_venues_for_window import annotate_city
            flag_result = annotate_city(city_key, db_path=db_path)
            flags_written = flag_result.get("annotated", 0)
            if flag_result.get("status") == "ok":
                flag_counts = flag_result.get("flag_counts", {})
                active = sum(1 for v in flag_counts.values() if v > 0)
                print(f"  [x] {flags_written} venues annotated "
                      f"({active} with active flags)")
            elif flag_result.get("status") == "skipped":
                print(f"  ~ {flag_result.get('note','No annotator for this city')}")
            else:
                print(f"  ⚠ Annotation status: {flag_result.get('status')}")
        except Exception as e:
            print(f"  ⚠ Window flag annotation failed: {e}")
    else:
        print("\n[11] Window flag annotation skipped (dry-run)")

    return {
        "city":                   city,
        "total_briefs":           len(briefs),
        "succeeded":              len(successes),
        "failed":                 len(failures),
        "failures":               failures,
        "validation_passed":      validation["passed"],
        "validation_issues":      validation["issues"],
        "validation_warnings":    validation["warnings"],
        "stats":                  validation["stats"],
        "events_written":         total_events_written,
        "windows_processed":      windows_processed,
        "matrix_pairs":           matrix_pairs,
        "ticket_rows":            ticket_rows,
        "venue_difficulty_count": venue_difficulty_count,
        "venue_events_written":   events_written,
        "venue_flags_written":    flags_written,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate full venue pool for a TravelBench city"
    )
    parser.add_argument("--city", required=True, help="City name e.g. 'london', 'tokyo'")
    parser.add_argument("--run-name", default=None,
                        help="Run name for separate DB (e.g. test_30). Default: production DB.")
    parser.add_argument("--api-key", default=None,
                        help="DeepSeek API key for RESEARCH_CITY and per-venue agent (steps 1 & 3)")
    parser.add_argument("--anthropic-key", default=None,
                        help="Anthropic API key for PLAN_VENUES + events (step 2). "
                             "Falls back to $ANTHROPIC_API_KEY env var if not set.")
    parser.add_argument("--model", default="deepseek-chat",
                        help="Model for per-venue agent loop")
    parser.add_argument("--planning-model", default="claude-sonnet-4-6",
                        help="Model for PLAN_VENUES + RESEARCH_CITY (default: claude-sonnet-4-6)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Use stub data, no API calls")
    parser.add_argument("--workers", type=int, default=5,
                        help="Parallel workers for venue generation (default 5)")
    parser.add_argument("--verbose", action="store_true",
                        help="Show agent turn-by-turn output")
    parser.add_argument("--limit", type=int, default=None,
                        help="Cap number of venues to generate (e.g. --limit 10 for a quick test)")
    parser.add_argument("--wrong-info-only", action="store_true",
                        help="Only generate venues with wrong info planned (mid/low traffic tier only)")
    parser.add_argument("--window", default=None,
                        help="Specific window_id to generate events for (default: all windows for city)")
    parser.add_argument("--ors-key", default=None,
                        help="OpenRouteService API key for real walking times (optional, uses haversine if omitted)")
    parser.add_argument("--skip-matrix", action="store_true",
                        help="Skip travel matrix computation (step 7)")
    parser.add_argument("--skip-tickets", action="store_true",
                        help="Skip ticket availability population (step 8)")
    parser.add_argument("--skip-venue-difficulty", action="store_true",
                        help="Skip venue difficulty score computation (step 9)")
    parser.add_argument("--db", type=Path, default=None,
                        help="Override DB path (default: data/cities/{city}/travelbench.db)")
    args = parser.parse_args()

    _anthropic_key = (
        None if args.dry_run else
        (args.anthropic_key or os.environ.get("ANTHROPIC_API_KEY"))
    )

    _db = args.db or get_city_db_path(args.city, run_name=getattr(args,'run_name',None))
    init_db(_db)
    result = generate_city_venues(
        city=args.city,
        api_key=None if args.dry_run else args.api_key,
        anthropic_key=_anthropic_key,
        model=args.model,
        planning_model=getattr(args, "planning_model", None),
        dry_run=args.dry_run,
        workers=args.workers,
        verbose=args.verbose,
        limit=args.limit,
        wrong_info_only=args.wrong_info_only,
        window_id=getattr(args, "window", None),
        db_path=_db,
    )

    print(f"\n{'='*60}")
    print(f"SUMMARY: {result['succeeded']}/{result['total_briefs']} venues generated")
    if result["failures"]:
        print("Failed venues:")
        for f in result["failures"]:
            print(f"  - {f.get('brief_name', '?')}: {f.get('message', f.get('error', '?'))}")
    print(f"Validation: {'PASSED' if result['validation_passed'] else 'FAILED'}")
    if result.get("events_written"):
        print(f"Events written: {result['events_written']} across {len(result.get('windows_processed',[]))} window(s)")
