"""
scripts/generation/generate_venue.py

Per-venue agent loop. Takes a city and venue brief, runs one Claude agent
with the 8 generation tools, and produces a complete verified venue package
in the DB (ground truth + Yelp listing + source docs + official site).

Usage:
  python scripts/generation/generate_venue.py \\
    --city london --category restaurant --district Soho \\
    --traffic-tier mid --api-key KEY

  python scripts/generation/generate_venue.py \\
    --city london --category cafe --district Camden \\
    --traffic-tier low --dry-run
"""

import json
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from scripts.generation.db import get_connection, DB_PATH, get_city_db_path
from scripts.generation.agent_tools import dispatch

try:
    from openai import OpenAI
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False

# ─────────────────────────────────────────────────────────────────────────────
# PRE-LOAD HANDBOOK PAGES
# Injected into SYSTEM_PROMPT so they sit in the stable prefix — this lets
# DeepSeek's prefix cache cover them across all 40 venue agents in a run,
# billing at ~10% of normal input token rate instead of full price per call.
# Agents do not need to call HELP() for these pages.
# ─────────────────────────────────────────────────────────────────────────────
from scripts.generation.handbook import query_handbook

_HANDBOOK_BASE = "\n\n".join([
    "## Pre-loaded handbook reference\n"
    "The following pages are already loaded — no need to HELP() query them.\n"
    "You may still call HELP() for any page not listed here.",

    "### Tool index  [HELP(\"-h function\")]",
    query_handbook("-h function"),

    "### Traffic tier guide  [HELP(\"-h format traffic_tier\")]",
    query_handbook("-h format traffic_tier"),

    "### Venue schema  [HELP(\"-h format venue\")]",
    query_handbook("-h format venue"),
])

_WRONG_INFO_RULES_SECTION = "\n\n".join([
    "### Wrong info rules  [HELP(\"-h format wrong_info_rules\")]",
    query_handbook("-h format wrong_info_rules"),
])

_SYSTEM_PROMPT_BODY = """You are a data generation agent for TravelBench, a benchmark that evaluates
LLM travel planning agents. Your job is to generate one complete, internally
consistent venue package for a city dataset. Accuracy, realism, and internal
consistency are the priority.

## Your workflow
Work like a git commit flow:
1. CREATE_PAGE for each document you need to produce
2. FILL the page fields — batch fill, override freely until satisfied
3. COMMIT when a page is complete — runs completeness check, lets you review
4. VERIFY("all") when all pages are committed — runs consistency checks
5. SUBMIT if VERIFY passes

Use THINK freely whenever you are uncertain about a decision, want to reason
through a design choice, or need to plan your next steps. It costs nothing
and creates an audit trail of your reasoning.
After a failed VERIFY: calling THINK is mandatory before redrafting. Read the
error report carefully, call THINK with your analysis and fix plan, then
proceed. Do not patch — fix only the specific failing issue.

## Important: what you do NOT need to provide
- City: injected automatically into every tool call — never pass it yourself
- venue_id for new venues: auto-generated by CREATE_PAGE — just call CREATE_PAGE("venue")
- venue_id for yelp_listing / official_site_doc: use the record_id returned by CREATE_PAGE("venue")

## Quality principles
- Yelp partial labels should reflect how an owner presents their venue —
  selling points and eye-catching features, not a random subset.
- Blog and forum prose must read as natural human writing.
- Tags should be accurate and specific. Query HELP("-h format tags") for tag conventions.

## Source doc diversity
Each source doc for a venue must feel unmistakably written by a different person.
Persona AND tone must both be distinct — two docs that share a persona or share a tone
are not diverse enough, even if the content differs.

PERSONA (CLOSED VOCAB — pick exactly one per doc, never reuse within a venue):
  tourist on first visit   Wide-eyed, over-explains obvious things, no local knowledge
  local regular            Casual and assuming, references past visits, drops neighbourhood slang
  travel photographer      Visual and sensory, notices light and atmosphere, mentions composition
  food blogger             Opinionated on specific dishes, compares to other places, grades granularly
  parent with kids         Laser-focused on practicalities: kids' menu, noise, toilet access
  solo traveller           Notes staff warmth, solo-dining vibe, mentions ease of getting a table
  accessibility visitor    Specifically notices ramps, door width, spacing between tables, staff help

TONE (OPEN VOCAB — these 10 are the suggested buckets; INVENT a new descriptor
when none fits naturally; aim for tone variety across docs of the same venue):
  talkative / rambling      Long sentences, lots of "and also..." and "oh and...", tangents
  terse / factual           Short clipped sentences, minimal adjectives, reads like a checklist
  emotional / sensory       Focuses on feeling and atmosphere: "golden afternoon light..."
  analytical / measured     Hedges claims ("probably", "seemed like"), compares pros and cons
  wry / observational       Dry humour, ironic distance, "not what I expected"
  nostalgic / reflective    Looks back, references previous visits or how the place used to be
  instructional / how-to    Second-person guidance: "if you go, do X first"
  complaint-first / grouchy Opens with frustration or skepticism, may warm up later
  journalistic / detached   Third-person voice, press-release / travel-magazine feel
  confessional / personal   Frames the visit around the author's mood: "had a rough week so I..."

For every source_doc, FILL the `persona` and `tone` fields explicitly — both
are REQUIRED at COMMIT and persona has a hard within-venue uniqueness check.

CREATE_PAGE("source_doc", venue_id=...) returns four context fields you should
USE when picking persona and tone:
  - personas_still_available: pick from this list — others are already taken
  - tones_used_for_venue: avoid repeating tones already on this venue's docs
  - city_tone_counts + city_tone_target_per_bucket: soft city-wide spread
    target. If a tone is well below target (e.g. 2/21), strongly prefer it.
    If it's near target, fine to use. If well above, pick something else or
    invent a new descriptor. The `_invented` bucket aggregates all
    non-canonical tones — feel free to coin new ones when the 10 don't fit.

## mentioned_regulations ↔ body content (strict coupling)
The body must mention a regulation if and only if it appears in mentioned_regulations.
  - wheelchair_accessible IS in mentioned_regulations  →  body must reference it naturally
  - pet_friendly is NOT in mentioned_regulations       →  body must NOT mention pets at all
Do not casually drop a regulation fact into the body without listing it in mentioned_regulations.
Do not list a tag in mentioned_regulations that the body does not actually address.
Each doc covers 1–2 regulations maximum (VERIFY enforces the 2-tag limit).
Spread regulations across docs — each doc picks the 1–2 that fit its author's perspective.
Never write a run-on sentence that lists every regulation at once. One well-placed detail
per regulation, woven into the author's own experience, is the correct pattern.

"""

# Two cached system prompts — built once at import, reused across parallel workers.
# Venues with wrong_info get the full prompt (includes ~3.8k token wrong_info_rules).
# Clean venues get the leaner prompt — no wrong info rules, no incorrect/truth-carrier guidance.
SYSTEM_PROMPT_WRONG_INFO = (
    _SYSTEM_PROMPT_BODY
    + "## Your tools (11 total)\n"
    + "The tool index, wrong info rules, traffic tier guide, and venue schema are\n"
    + "pre-loaded at the bottom of this prompt — no need to HELP() query them.\n"
    + "You may call HELP() for any other page (e.g. HELP(\"-h format source_doc\")).\n\n"
    + "Incorrect source docs must show no awareness the information might be wrong.\n"
    + "Truth carrier docs: embed the correction in 1-2 sentences of natural experience prose.\n"
    + "  Cross-referencing another source is fine. Pointing out the discrepancy is fine.\n"
    + "  Do NOT over-elaborate: no origin story, no proving yourself right, no repeating the fact.\n"
    + "  WRONG: multi-sentence explanation of why/how the info changed.\n"
    + "  RIGHT: 'They close at 21:00 now; Yelp still shows 20:00.' — brief, done.\n\n"
    + "## WRONG-INFO WORKFLOW (P6-T22) — atomic 4-step chain\n"
    + "ADD_WRONG_INFO is now ATOMIC: it creates the wrong_info entry AND registers\n"
    + "both required source-doc roles in one transactional call. You do NOT need to\n"
    + "call REGISTER_DOC_REFS for the wrong-info roles. The chain is:\n\n"
    + "  Step 1.  CREATE_PAGE + FILL + COMMIT for the INCORRECT SOURCE doc\n"
    + "           — body embeds the wrong value with no awareness it's wrong.\n"
    + "  Step 2.  CREATE_PAGE + FILL + COMMIT for the TRUTH CARRIER doc\n"
    + "           — body embeds the correction in 1-2 sentences of natural prose.\n"
    + "  Step 3.  (If source_type='yelp') FILL the yelp_listing yelp_<field> with\n"
    + "           the incorrect value (so it surfaces in search_yelp output).\n"
    + "  Step 4.  ADD_WRONG_INFO(\n"
    + "             venue_id=V,\n"
    + "             affected_field='hours_fri',\n"
    + "             incorrect_value='20:00',\n"
    + "             correct_value='22:00',\n"
    + "             source_type='blog',\n"
    + "             wrong_info_category='temporal_decay',\n"
    + "             origin_story='Owner registered hours years ago and never updated.',\n"
    + "             incorrect_source_doc_id=A,    # doc from Step 1\n"
    + "             truth_carrier_doc_id=B,       # doc from Step 2\n"
    + "           )\n"
    + "           — atomic; creates wrong_info AND registers both docs.\n\n"
    + "Multi-wrong-info venues: call ADD_WRONG_INFO once per wrong_info entry,\n"
    + "each with its OWN pair of doc_ids. A single doc can't be the truth_carrier\n"
    + "(or incorrect_source) for two different wrong_info entries on the same venue\n"
    + "— spin up a fresh doc per entry.\n\n"
    + _HANDBOOK_BASE + "\n\n" + _WRONG_INFO_RULES_SECTION
)

SYSTEM_PROMPT_CLEAN = (
    _SYSTEM_PROMPT_BODY
    + "## Your tools (11 total)\n"
    + "The tool index, traffic tier guide, and venue schema are\n"
    + "pre-loaded at the bottom of this prompt — no need to HELP() query them.\n"
    + "You may call HELP() for any other page (e.g. HELP(\"-h format source_doc\")).\n"
    + "This venue has no wrong information — do NOT call ADD_WRONG_INFO.\n\n"
    + _HANDBOOK_BASE
)

# Keep a default alias for code that imports SYSTEM_PROMPT directly
SYSTEM_PROMPT = SYSTEM_PROMPT_WRONG_INFO



# Wrong info suggestions — sampled randomly per call (thread-safe, no shared state)
# Intentionally balanced: hours appears only once to avoid over-indexing on time traps.
_WRONG_INFO_SUGGESTIONS = [
    ("temporal_decay",   "hours_*",
     "incorrect window — source shows venue opening earlier AND closing later than it actually does now"),
    ("temporal_decay",   "avg_cost_local / price_tier",
     "price was higher when source was written; venue has since reduced prices"),
    ("temporal_decay",   "avg_cost_local / price_tier",
     "price was lower when source was written; venue has since raised prices (renovation, new ownership)"),
    ("temporal_decay",   "booking_required",
     "booking policy changed; source says walk-in welcome but venue now requires reservation"),
    ("temporal_decay",   "booking_required",
     "booking policy reversed; source says reservation required but venue now accepts walk-ins"),
    ("temporal_decay",   "recommended_visit_minutes",
     "visit duration was longer when source was written; venue has since reduced its offering or scope"),
    ("temporal_decay",   "noise_level",
     "venue was quieter when source was written; has since become louder (popularity, new format, live events)"),
    ("temporal_decay",   "a tag or label in blog/forum prose",
     "a label that was accurate when written (live-music, outdoor-seating, popular-with-locals) but no longer applies"),
    ("conditional",      "avg_cost_local or booking_required",
     "seasonal or event-day change — source written in a different season or before a policy shift"),
    ("conditional",      "hours_*",
     "holiday or seasonal hours — source lists normal hours with no awareness the venue closes early (or fully) on certain days"),
]


def _next_wrong_info_suggestion() -> str:
    import random
    cat, field, desc = random.choice(_WRONG_INFO_SUGGESTIONS)
    return (
        f"Wrong info: YES — add at least one entry using ADD_WRONG_INFO.\n"
        f"  Suggested type: {cat} on {field}\n"
        f"  Suggested scenario: {desc}\n"
        f"  You may vary this if a different type fits the venue character better.\n"
        f"  Multiple entries allowed if the venue character supports it (neglected, unreliable).\n"
        f"  Query HELP(\"-h format wrong_info_rules\") before deciding."
    )


def _build_assignment(city: str, category: str, district: str,
                       traffic_tier: str, name: str = None,
                       archetype: str = None,
                       has_wrong_info: bool = False,
                       recommended_pace: str = None,
                       coverage_tags: list = None,
                       overpass_ref: dict = None,
                       event_briefs: list[dict] = None,
                       regulation_directives: dict = None,
                       db_path: Path = DB_PATH) -> str:
    """Build the assignment block injected at the end of the user message."""
    lines = [
        "## Your assignment",
        f"City: {city}",
    ]
    if name:
        lines.append(f"Venue name: {name}  ← use this exact name")
    lines += [
        f"Venue category: {category}",
        f"District: {district}",
        f"Traffic tier: {traffic_tier}",
    ]
    if archetype:
        lines.append(f"Venue character: {archetype}")
    if overpass_ref:
        lines.append("")
        lines.append("Reference data from OpenStreetMap (use as starting point — do not treat as ground truth):")
        if overpass_ref.get("lat"):
            lines.append(f"  Coordinates: {overpass_ref['lat']}, {overpass_ref['lng']}")
        if overpass_ref.get("address"):
            lines.append(f"  Address: {overpass_ref['address']}")
        if overpass_ref.get("policies"):
            for k, v in overpass_ref["policies"].items():
                lines.append(f"  {k}: {v}")
        lines.append("  Note: invent opening hours yourself — do not use any hours from external sources.")
    lines.append("")
    lines.append("The venue name above is the exact name to use — do not invent a different one.")
    lines.append("")
    if recommended_pace:
        lines.append(f"recommended_pace: {recommended_pace}  ← use this assigned value")
        lines.append("  Only override if the venue type clearly contradicts this assignment.")
    else:
        lines.append("recommended_pace must be exactly one of: relaxed | moderate | intense")
        lines.append("  relaxed: parks, canal walks, cafes, neighbourhood strolls — no time pressure")
        lines.append("  moderate: most restaurants, galleries, pubs, markets — typical visit pacing")
        lines.append("  intense: major museums, ticketed attractions, Michelin restaurants — busy, demanding")
        lines.append("  Pick based on venue character — do NOT default everything to relaxed or moderate.")
    if coverage_tags:
        lines.append(f"coverage_tags (must include in SET_TAGS): {coverage_tags}")
        lines.append("  These tags are pool-level assignments — include them as yelp_visible=1.")
        lines.append("  Add more tags freely based on the venue character.")

    # ── P6-T1: Canonical tag vocabulary ───────────────────────────────────────
    # SET_TAGS hard-rejects any tag not in the city's combined vocabulary
    # (universal core + universal cuisines + city extension). Show the agent
    # the vocabulary up front so it picks from the list rather than inventing.
    from scripts.generation.handbook import format_vocab_by_axis
    city_extension: list[str] = []
    try:
        conn = get_connection(db_path)
        cc_row = conn.execute(
            "SELECT tag_vocabulary FROM city_config WHERE city = ?", (city,)
        ).fetchone()
        if cc_row and cc_row[0]:
            try:
                city_extension = json.loads(cc_row[0])
            except Exception:
                city_extension = []
        # Also show existing usage counts as guidance (no enforcement role)
        existing_counts = list(conn.execute(
            "SELECT tag, COUNT(*) AS n FROM tags WHERE city=? "
            "GROUP BY tag ORDER BY n DESC, tag", (city,)
        ).fetchall())
        conn.close()
    except Exception:
        existing_counts = []

    lines.append("")
    lines.append("## Tag vocabulary — SET_TAGS hard-rejects anything off-vocab")
    lines.append(format_vocab_by_axis(city_extension))
    lines.append("")
    lines.append("  Tag format: hyphenated kebab-case only (free-entry, hidden-gem, instagrammable).")
    lines.append("  Max 15 tags per venue (12+ triggers a high-count warning).")
    if existing_counts:
        # Show top-15 by usage as a guidance signal (not a constraint).
        top = ", ".join(f"{r[0]}({r[1]})" for r in existing_counts[:15])
        lines.append(f"  Most-used in this city so far: {top}")

    lines.append("")
    if has_wrong_info:
        lines.append(_next_wrong_info_suggestion())
    else:
        lines.append("Wrong info: NO — do not call ADD_WRONG_INFO for this venue.")
        lines.append("  This venue must have clean, consistent data across all sources.")

    # ── Regulation steering directives (auto-assigned for benchmark diversity) ─
    if regulation_directives:
        lines.append("")
        lines.append("## REGULATION DIRECTIVES (auto-assigned for benchmark diversity)")
        lines.append("The following regulation values are required for this venue to")
        lines.append("balance the city pool. Set these values via SET_FIELD:")
        for reg_field, (reg_val, reason) in regulation_directives.items():
            val_str = "1 (true)" if reg_val else "0 (false)"
            lines.append(f"  {reg_field} = {val_str}  — {reason}")
        lines.append("Make sure these values are natural for the venue character.")
        lines.append("Mention the relevant regulation in at least one source doc body.")

    # ── EVENTS block ──────────────────────────────────────────────────────────
    if event_briefs:
        lines.append("")
        lines.append("## Events assigned to this venue")
        lines.append("These events are confirmed facts. You MUST incorporate them into source docs.")
        lines.append("")
        lines.append("REQUIREMENTS (verified by VERIFY):")
        lines.append("  - Official site doc MUST mention each event and its booking/access status")
        lines.append("  - At least one source doc (blog or forum) MUST mention each event naturally")
        lines.append("  - Do NOT reveal specific sold-out dates in prose — convey urgency instead")
        lines.append("    e.g. 'sells out fast on key dates' not 'sold out 2026-04-05'")
        lines.append("")
        for ev in event_briefs:
            lines.append(f"EVENT: {ev.get('name', '?')}")
            lines.append(f"  Window: {ev.get('window_id', '?')}")
            lines.append(f"  Dates: {ev.get('start_date','')} to {ev.get('end_date','')}")
            if ev.get("affects_hours"):
                lines.append(f"  Hours change: {ev.get('modified_hours', 'modified during event')}")
            if ev.get("affects_access"):
                lines.append("  Access: advance booking required")
            if ev.get("sold_out") or ev.get("sold_out_dates"):
                lines.append("  Availability: some dates are sold out — mention booking urgency")
            if ev.get("price_local"):
                lines.append(f"  Price: ${ev['price_local']:.0f}")
            if ev.get("source_hint"):
                lines.append(f"  Official site hint: \"{ev['source_hint']}\"")
            lines.append(f"  Description: {ev.get('description', '')}")
            lines.append("")

    lines.append("")
    lines.append("Begin with CREATE_PAGE(\"venue\") and proceed through the workflow.")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# TOOL SCHEMAS FOR CLAUDE API
# ─────────────────────────────────────────────────────────────────────────────

TOOL_SCHEMAS = [
    {
        "type": "function",
        "function": {
            "name": "HELP",
            "description": "Query the handbook for tool specs and format schemas.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string",
                              "description": "A -h style query e.g. '-h function FILL' or '-h format venue'"}
                },
                "required": ["query"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "CREATE_PAGE",
            "description": "Create an empty DB page for an entity. Returns page_id, record_id, and required fields.",
            "parameters": {
                "type": "object",
                "properties": {
                    "entity_type": {"type": "string",
                                    "enum": ["venue", "yelp_listing", "source_doc", "official_site_doc"]},
                    "venue_id": {"type": "string",
                                 "description": "Required for yelp_listing, source_doc, and official_site_doc. For source_doc, this is the doc's PRIMARY venue; additional venues can be linked post-COMMIT via REGISTER_DOC_REFS. For venue, leave empty — a new ID will be generated and returned."}
                },
                "required": ["entity_type"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "FILL",
            "description": "Batch-fill fields on a page. Accepts any field name for the entity type.",
            "parameters": {
                "type": "object",
                "properties": {
                    "page_id": {"type": "string"},
                    "fields": {"type": "object",
                               "description": "Dict of field names to values."}
                },
                "required": ["page_id", "fields"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "COMMIT",
            "description": "Run completeness check and lock the page.",
            "parameters": {
                "type": "object",
                "properties": {
                    "page_id": {"type": "string"}
                },
                "required": ["page_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "VERIFY",
            "description": "Run all consistency checks on committed pages. Pass 'all' to check everything.",
            "parameters": {
                "type": "object",
                "properties": {
                    "target": {"type": "string", "description": "Pass 'all'"},
                    "venue_id": {"type": "string", "description": "The venue_id to verify"}
                },
                "required": ["target", "venue_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "GET_STATUS",
            "description": "Check current state of all pages for this venue.",
            "parameters": {
                "type": "object",
                "properties": {
                    "venue_id": {"type": "string"}
                },
                "required": ["venue_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "THINK",
            "description": "Log correction plan after failed VERIFY. Call before redrafting.",
            "parameters": {
                "type": "object",
                "properties": {
                    "thought": {"type": "string",
                                "description": "Detailed plan explaining what went wrong and how to fix it."}
                },
                "required": ["thought"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "SET_TAGS",
            "description": "Set all tags for a venue. Tags do not go in FILL — use this dedicated tool.",
            "parameters": {
                "type": "object",
                "properties": {
                    "venue_id": {"type": "string", "description": "The venue_id"},
                    "tags": {
                        "type": "array",
                        "description": "List of tag objects. Each has 'tag' (string) and 'yelp_visible' (0 or 1).",
                        "items": {
                            "type": "object",
                            "properties": {
                                "tag": {"type": "string"},
                                "yelp_visible": {"type": "integer", "enum": [0, 1]}
                            },
                            "required": ["tag", "yelp_visible"]
                        }
                    }
                },
                "required": ["venue_id", "tags"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "REGISTER_DOC_REFS",
            "description": "Register that a source_doc mentions a venue and set its role. Call after COMMITting each source_doc.",
            "parameters": {
                "type": "object",
                "properties": {
                    "doc_id": {"type": "string", "description": "The record_id returned by CREATE_PAGE for source_doc"},
                    "venue_id": {"type": "string"},
                    "role": {"type": "string", "enum": ["neutral", "incorrect_source", "truth_carrier"]},
                    "wrong_info_id": {"type": "string", "description": "Required if role is truth_carrier or incorrect_source. Use ID from ADD_WRONG_INFO."}
                },
                "required": ["doc_id", "venue_id", "role"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "ADD_WRONG_INFO",
            "description": "Atomically create a wrong_info entry AND register both required source-doc roles (incorrect_source + truth_carrier). Both docs must already be COMMITted. Replaces the old multi-call chain — you do NOT need to call REGISTER_DOC_REFS separately for these roles.",
            "parameters": {
                "type": "object",
                "properties": {
                    "venue_id": {"type": "string"},
                    "affected_field": {"type": "string", "description": "e.g. 'hours_fri', 'hours_mon'"},
                    "incorrect_value": {"type": "string", "description": "The wrong value that appears in the incorrect source"},
                    "correct_value": {"type": "string", "description": "The correct value in ground truth"},
                    "source_type": {"type": "string", "enum": ["yelp", "blog", "forum"]},
                    "wrong_info_category": {"type": "string", "enum": ["temporal_decay", "propagation_error", "conditional", "subjective"]},
                    "origin_story": {"type": "string", "description": "One sentence explaining how this mistake plausibly entered this source"},
                    "incorrect_source_doc_id": {"type": "string", "description": "doc_id of the committed source_doc whose body carries the WRONG value (with no awareness it's wrong). Required."},
                    "truth_carrier_doc_id":    {"type": "string", "description": "doc_id of the committed source_doc whose body carries the correction (embedded naturally in experience prose). Required. Must differ from incorrect_source_doc_id."}
                },
                "required": ["venue_id", "affected_field", "incorrect_value", "correct_value", "source_type", "wrong_info_category", "origin_story", "incorrect_source_doc_id", "truth_carrier_doc_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "SUBMIT",
            "description": "Mark venue complete. Only callable after VERIFY passes.",
            "parameters": {
                "type": "object",
                "properties": {
                    "venue_id": {"type": "string"}
                },
                "required": ["venue_id"]
            }
        }
    }
]


# ─────────────────────────────────────────────────────────────────────────────
# AGENT LOOP
# ─────────────────────────────────────────────────────────────────────────────

MAX_TURNS = 60  # raised — complex venues with wrong info need ~30-45 turns


def run_venue_agent(city: str, category: str, district: str,
                    traffic_tier: str, name: str = None,
                    archetype: str = None, has_wrong_info: bool = False,
                    recommended_pace: str = None,
                    coverage_tags: list = None,
                    overpass_ref: dict = None,
                    event_briefs: list[dict] = None,
                    regulation_directives: dict = None,
                    api_key: str = None, model: str = "claude-sonnet-4-20250514",
                    db_path: Path = DB_PATH,
                    verbose: bool = False,
                    log_path: Path = None) -> dict:
    """
    Run the venue generation agent. Returns a result dict with status and venue_id.
    If log_path is set, writes the full conversation to a JSON file.
    event_briefs: list of event dicts assigned to this venue (from Step 4).
    """
    if not HAS_OPENAI or not api_key:
        return _dry_run_result(city, category, district, traffic_tier, name, db_path,
                               overpass_ref=overpass_ref,
                               has_wrong_info=has_wrong_info)

    _planned_wrong_info = has_wrong_info
    _event_briefs = event_briefs or []

    conversation_log = {
        "city": city, "category": category, "district": district,
        "traffic_tier": traffic_tier, "name": name, "model": model,
        "turns": []
    }

    def _save_log():
        if log_path:
            log_path.parent.mkdir(parents=True, exist_ok=True)
            with open(log_path, "w") as f:
                json.dump(conversation_log, f, indent=2, ensure_ascii=False, default=str)

    client = OpenAI(
        api_key=api_key,
        base_url="https://api.deepseek.com"
    )
    system_prompt = SYSTEM_PROMPT_WRONG_INFO if has_wrong_info else SYSTEM_PROMPT_CLEAN
    assignment = _build_assignment(
        city, category, district, traffic_tier, name, archetype,
        recommended_pace=recommended_pace,
        coverage_tags=coverage_tags,
        has_wrong_info=has_wrong_info,
        event_briefs=_event_briefs,
        regulation_directives=regulation_directives,
        db_path=db_path,
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": assignment}
    ]

    turn = 0
    submitted_venue_id = None

    while turn < MAX_TURNS:
        turn += 1
        response = client.chat.completions.create(
            model=model,
            max_tokens=4096,
            tools=TOOL_SCHEMAS,
            messages=messages,
            stream=False
        )

        msg = response.choices[0].message
        finish_reason = response.choices[0].finish_reason

        messages.append(msg.model_dump(exclude_unset=False))

        if finish_reason == "stop":
            break

        if finish_reason != "tool_calls" or not msg.tool_calls:
            break

        for tc in msg.tool_calls:
            tool_name = tc.function.name
            try:
                tool_input = json.loads(tc.function.arguments)
            except json.JSONDecodeError:
                tool_input = {}

            tool_input_clean = {k: v for k, v in tool_input.items()
                                if k not in ("db_path", "city")}
            tool_input["db_path"] = db_path
            tool_input["city"]    = city
            # P6-T1: SET_TAGS uses these for the DeepSeek "did you mean" call
            # when a tag falls outside the canonical vocabulary.
            tool_input["api_key"] = api_key
            tool_input["model"]   = model
            # Inject event_briefs into VERIFY so it can check event mention coverage
            if tool_name == "VERIFY" and _event_briefs:
                tool_input["event_briefs"] = _event_briefs
            result = dispatch(tool_name, **tool_input)

            if (tool_name == "CREATE_PAGE"
                    and tool_input.get("entity_type") == "venue"
                    and result.get("status") == "created"):
                from scripts.generation.db import get_connection as _gc
                _c = _gc(db_path)
                _c.execute(
                    "UPDATE venues SET has_wrong_info_planned = ? WHERE venue_id = ?",
                    (1 if _planned_wrong_info else 0, result["record_id"])
                )
                _c.commit()
                _c.close()

            conversation_log["turns"].append({
                "turn": turn,
                "tool": tool_name,
                "input": tool_input_clean,
                "result": result
            })
            _save_log()

            if tool_name == "SUBMIT" and result.get("status") == "submitted":
                submitted_venue_id = result.get("venue_id")

            messages.append({
                "role": "tool",
                "tool_call_id": tc.id,
                "content": json.dumps(result, ensure_ascii=False)
            })

        if submitted_venue_id:
            break

    conversation_log["final_status"] = "success" if submitted_venue_id else "failed"
    conversation_log["total_turns"] = turn
    conversation_log["venue_id"] = submitted_venue_id
    _save_log()

    if submitted_venue_id:
        if log_path:
            print(f"  📄 Conversation log saved: {log_path}")
        return {
            "status": "success",
            "venue_id": submitted_venue_id,
            "turns": turn,
            "city": city,
            "category": category,
            "district": district,
            "log_path": str(log_path) if log_path else None,
        }
    else:
        if log_path:
            print(f"  📄 Conversation log saved: {log_path}")
        return {
            "status": "failed",
            "turns": turn,
            "city": city,
            "category": category,
            "district": district,
            "message": "Agent did not SUBMIT within turn limit",
            "log_path": str(log_path) if log_path else None,
        }


def _dry_run_result(city: str, category: str, district: str,
                    traffic_tier: str, name: str = None, db_path: Path = DB_PATH,
                    overpass_ref: dict = None,
                    has_wrong_info: bool = False) -> dict:
    """
    Dry run: insert a minimal stub venue directly to DB without LLM.
    Uses overpass_ref coordinates if available.
    """
    from scripts.generation.db import (
        new_venue_id, new_doc_id, new_page_id, get_connection
    )
    import random

    vid = new_venue_id()
    conn = get_connection(db_path)

    # Check city exists
    city_row = conn.execute("SELECT * FROM city_config WHERE city = ?", (city,)).fetchone()
    if city_row is None:
        conn.close()
        return {"status": "error", "message": f"City '{city}' not in DB. Run research_city first."}

    # Popularity score from tier
    tier_ranges = {"high": (0.7, 1.0), "mid": (0.4, 0.7), "low": (0.1, 0.4)}
    lo, hi = tier_ranges.get(traffic_tier, (0.3, 0.6))
    pop_score = round(random.uniform(lo, hi), 3)
    total_results = {"high": random.randint(500, 3000),
                     "mid": random.randint(50, 499),
                     "low": random.randint(4, 49)}.get(traffic_tier, 50)

    stub_name = name or f"Stub {category.title()} in {district}"

    # Use Overpass coordinates if available, otherwise random scatter
    if overpass_ref and overpass_ref.get("lat"):
        stub_lat = overpass_ref["lat"]
        stub_lng = overpass_ref["lng"]
    else:
        stub_lat = city_row["centre_lat"] + random.uniform(-0.02, 0.02)
        stub_lng = city_row["centre_lng"] + random.uniform(-0.02, 0.02)

    # Insert venue
    conn.execute("""
        INSERT INTO venues (venue_id, city, name, category, district,
            lat, lng, avg_cost_local, price_tier, recommended_visit_minutes,
            booking_required, has_official_site, outdoor_sensitivity,
            recommended_pace, traffic_tier, total_results, yelp_popularity_score,
            pet_friendly, wheelchair_accessible, parking_nearby,
            photography_allowed, noise_level, reservation_required,
            outside_food_allowed, family_friendly, food_available,
            has_wrong_info_planned, page_status)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        vid, city, stub_name, category, district,
        stub_lat, stub_lng,
        20.0, "mid", 60, 0, 0, "indoor", "moderate",
        traffic_tier, total_results, pop_score,
        1, 1, 0, 1, "moderate", 0, 0, 1,
        1 if category in ("restaurant", "cafe", "bar") else 0,
        1 if has_wrong_info else 0,
        "verified"
    ))

    # Insert Yelp listing
    conn.execute("""
        INSERT INTO yelp_listings (venue_id, city, name, category, district,
            stars, review_count, yelp_popularity_score, page_status)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, (vid, city, stub_name, category, district,
          round(random.uniform(3.8, 4.8), 1), random.randint(10, 500),
          pop_score, "verified"))

    # Insert a stub source doc
    doc_id = new_doc_id()
    conn.execute("""
        INSERT INTO source_docs (doc_id, city, doc_type, title, author,
            source_name, date, body, page_status)
        VALUES (?,?,?,?,?,?,?,?,?)
    """, (doc_id, city, "blog", f"Visiting {district}",
          "Test Author", "StubBlog.com", "2025-01-01",
          f"A nice {category} in {district}. Wheelchair accessible. Family friendly.",
          "verified"))
    conn.execute("INSERT INTO doc_venue_refs (doc_id, venue_id) VALUES (?,?)", (doc_id, vid))

    # Add a stub tag
    conn.execute("INSERT OR IGNORE INTO tags (tag, city, venue_id, yelp_visible) VALUES (?,?,?,?)",
                 (category, city, vid, 1))

    conn.commit()
    conn.close()

    return {
        "status": "success",
        "venue_id": vid,
        "turns": 0,
        "city": city,
        "name": name or f"Stub {category.title()} in {district}",
        "category": category,
        "district": district,
        "dry_run": True
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--city", required=True)
    parser.add_argument("--category", required=True,
                        choices=["restaurant", "cafe", "bar", "museum",
                                 "attraction", "park", "neighbourhood"])
    parser.add_argument("--district", required=True)
    parser.add_argument("--traffic-tier", required=True, choices=["high", "mid", "low"])
    parser.add_argument("--name", default=None,
                        help="Exact venue name e.g. 'The Anchor and Crown'")
    parser.add_argument("--archetype", default=None,
                        help="One-sentence venue character description")
    parser.add_argument("--api-key", default=None)
    parser.add_argument("--model", default="claude-sonnet-4-20250514")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    init_db()
    result = run_venue_agent(
        city=args.city,
        category=args.category,
        district=args.district,
        traffic_tier=args.traffic_tier,
        name=args.name,
        archetype=args.archetype,
        api_key=None if args.dry_run else args.api_key,
        model=args.model,
        verbose=args.verbose
    )
    print(json.dumps(result, indent=2))
